### ISSUE TITLE
Which AI?

### ISSUE THREAD

**Issue by rossman22590** [reworkd/AgentGPT#1]
Where do I put my Open AI API Key or other AI Key?

**Comment by asim-shrestha** [comment]
If you're using the deployed version at https://agentgpt.reworkd.ai/, it uses a system account so you don't have to provide any OpenAI key. If you want to run the tool locally, you can provide your own OpenAI key within environment variables

```
# Prisma
DATABASE_URL="file:./db.sqlite"

# Next Auth
NEXTAUTH_SECRET=""
NEXTAUTH_URL=""

# Next Auth Discord Provider
DISCORD_CLIENT_ID=""
DISCORD_CLIENT_SECRET=""
OPENAI_API_KEY=""
```

The code currently uses the `gpt-3-turbo` model
