### ISSUE TITLE
 The server is started,but I can't connect the server, The error msg is "next exited with code 0"

### ISSUE THREAD

**Issue by liangxiaowucai** [reworkd/AgentGPT#1022]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

./setup.sh

### Current behaviour

![image](https://github.com/reworkd/AgentGPT/assets/42310513/96fba8ec-414b-4899-a2c5-30dee1339b39)

### Steps to reproduce

1. ./setup.sh
2. wait the server running

### Possible solution

I don't know .

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by jasangill1** [comment]
Hello @liangxiaowucai Are you using docker ? if so try to load your backend it should be on localhost:8000!!

**Comment by jasangill1** [comment]
Hello @liangxiaowucai i will be clsing soon due to inactivity please reply if you would will want assistance for this issue
