### ISSUE TITLE
Error attempting to connect to the server for agentgpt.reworkd.ai

### ISSUE THREAD

**Issue by HappyPony** [reworkd/AgentGPT#1029]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

AgentGPT formulates tasks to be done to achieve the goals, executes these tasks and displays the result.

### Current behaviour

AgentGPT displays `Error attempting to connect to the server.`
4 times, then the error message 
`All tasks have been completed. Stop...`
 is displayed.

### Steps to reproduce

1. I specified the agent name and destination 
2. clicked "Start". 

### Possible solution

Analyze logfiles on the server _agentgpt.reworkd.ai_

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by jasangill1** [comment]
Hello @HappyPony  Hey team, quick heads up guys!!! Our systems are in a bit of a funk right now. Our devs are working non-stop to till all systems are back online!! When did you start experiencing these issues?

**Comment by HappyPony** [comment]
I noticed the bug about an hour ago. Thank yo for https://agentgpt.reworkd.ai/ :-).

**Comment by jasangill1** [comment]
Hello, @HappyPony We just applied an update that should fix this issue please take a moment for it to update all the servers!! We appreciate your patience !! Please let us know if you are still experiencing these issues

**Comment by jasangill1** [comment]
Will be closing as problem has been resolved !!
