### ISSUE TITLE
the ability to rename agents after run is complete

### ISSUE THREAD

**Issue by HappyPony** [reworkd/AgentGPT#1030]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/reworkd/AgentGPT/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/reworkd/AgentGPT/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

rename agents after run is complete

### ✔️ Solution

Rename for _agents names_, as is currently possible for _chats_ in ChatGPT in the left column. This renaming is especially important to distinguish between agents with the same name "ABCName" that were used for **different tasks**.

### ❓ Alternatives

Cumbersome search in the agents, of which the most recent are arranged higher in the agent list.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by asim-shrestha** [comment]
Going to close as it's not a priority
