### ISSUE TITLE
Personalize agents with avatars

### ISSUE THREAD

**Issue by HappyPony** [reworkd/AgentGPT#1050]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/reworkd/AgentGPT/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/reworkd/AgentGPT/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Assigning an avatar to an AgentGPT

![Bildschirmfoto vom 2023-07-14 09-04-42](https://github.com/reworkd/AgentGPT/assets/3226308/1b673386-b0f9-47c8-9d47-30408adc1ce4)

### ✔️ Solution

Provide a small edit button when defining the target and offer the possibility to assign an avatar to this AgentGPT profile in the edit dialog that appears. 

### ❓ Alternatives

The navigation between the agents by name

### 📝 Additional Context

With such an avatar the navigation between the agents is similar to the navigation in Discord and other social networks.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by jasangill1** [comment]
Hello @HappyPony Would you like to try and implement this feature!!! Im here to help you get started on this !!!

**Comment by HappyPony** [comment]
Hi @jasangill1, I have experience in programming, developing web applications in different programming languages. I have not programmed in Python yet. AgentGPT is installed and running locally. 
Can you give me a hint, how do I find objects in the development environment that represent navigation column left in AgentGPT?

**Comment by mdabir1203** [comment]
@jasangill1  I would like to work for the avatar additional feature. Can you shed me a light on where to start

**Comment by HappyPony** [comment]
@mdabir1203 I am not familiar with the way of working and the division of labor in this project, but it looks to me like a possible solution for the realization of this feature is described in https://github.com/kevinlu1248/AgentGPT/issues/6 and https://github.com/kevinlu1248/AgentGPT/pull/7.

**Comment by jasangill1** [comment]
Hello @mdabir1203 I can assign the task to you !! I would start at the LeftsideBar understand that and then follow the links to the agent stores !!

**Comment by mdabir1203** [comment]
I would be glad to take a look at it

**Comment by asim-shrestha** [comment]
Going to close this as it's not a priority
