### ISSUE TITLE
Vercel fork with your repo issue deployment

### ISSUE THREAD

**Issue by johnfelipe** [reworkd/AgentGPT#1065]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

Have a vercel deployment 

### Current behaviour

https://agent-gpt-reworkd-fork-er1tuaksf-johnfelipe.vercel.app/?vercelToolbarCode=uUQtT6ViFAp7qCD

show error

404: NOT_FOUND
Code: NOT_FOUND
ID: iad1::6vgzn-1689507690852-c0096754555e

how can solve this pls?

### Steps to reproduce

1. fork your repo
2. create a project in vercel
3. Deploy in vercel
4. review deployment url

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by jasangill1** [comment]
Hello @johnfelipe so you can not deploy the entire application on vercel you would need something to host the backend as well, For example a service like AWS or heroku !!

**Comment by johnfelipe** [comment]
@jasangill1 can u add deployment for heroku pls in readme file or doc/heroku.md for example?

**Comment by jasangill1** [comment]
@johnfelipe Yeah forsure i'm actually working on our deployment docs currently!!!!

**Comment by johnfelipe** [comment]
@jasangill1 if u need tester, pls ping me

**Comment by awtkns** [comment]
[Railway](https://railway.app/) is another good service to easily deploy stuff, maybe we can include docs for that :)

**Comment by johnfelipe** [comment]
Yes
I want to deploy asap
Pls share steps for do it.

**Comment by jasangill1** [comment]
Hello @johnfelipe are you able to get the application to run locally?

**Comment by jasangill1** [comment]
Hello @johnfelipe we will be closing this issue as it is a duplicate please comment / watch this issue for updates : https://github.com/reworkd/AgentGPT/issues/975
