### ISSUE TITLE
I have some question in this project

### ISSUE THREAD

**Issue by Lee7goal** [reworkd/AgentGPT#111]
For example, if I give him a goal to create a web page, will he really end up giving the code for the page?

**Comment by voidxd** [comment]
From what I gather, it currently can't do that. It can only brainstorm. But additional capabilities that would include things like that are under development:
![image](https://user-images.githubusercontent.com/58847957/232012184-3d419ecb-5c63-4340-a5a8-773d6431f6bf.png)

**Comment by yourepicservices** [comment]
@Lee7goal any other questions?

**Comment by Lee7goal** [comment]
no questions, thank you
