### ISSUE TITLE
Feature Request: Have an individual task execute button

### ISSUE THREAD

**Issue by daga-fam** [reworkd/AgentGPT#113]
Not sure if this is in the roadmap, but it would be great if we could execute specific tasks from the lists one at a time manually as well. This would allow us to filter tasks that we dont find relevant and get some insights.

**Comment by Jacky-He** [comment]
@awtkns @yourepicservices @daga-fam Hey hope y'all are doing great! We're a group of university students interested in contributing to AgentGPT. If you don't mind, our team can look into the implementation of this feature in the upcoming weeks. We're thinking about having a switch that toggles between a "manual" and "autonomous" mode for the agent such that during manual mode, the user is able to select the task from the lists one at a time for the agent to execute. We will try to create a PR within 3 weeks.

**Comment by yourepicservices** [comment]
Thank you for your contribution, @Jacky-He! Looking forward to seeing the progress.

**Comment by asim-shrestha** [comment]
Looking forward to it @Jacky-He! 

I do like the idea of a manual / autonomous mode. 

We have a ticket out to allow for manual task addition already. On top of this, we can instead allow users to re-order the tasks within the list.

**Comment by jasangill1** [comment]
Will be closing as the PR was closed!! @Jacky-He Please join our discord and get in touch with me `@json` on discord if you would like to further contribute to the project!!
