### ISSUE TITLE
API key error

### ISSUE THREAD

**Issue by AS19771007** [reworkd/AgentGPT#1199]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

I believe that API should be accepted as there is a green tick on settings 

### Current behaviour

Your API key exceeded your current quota, please check your plan and billing details.

### Steps to reproduce

go to the agentgpt 3.5 
add goal 

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by jasangill1** [comment]
Hello @AS19771007 you have probably hit your daily run limit

**Comment by aayushgelal** [comment]
@AS19771007  You have to create a new account. I had the similar issue as well. Seems like OpenAi has a time limit for an account to use the API
