### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by rossman22590** [reworkd/AgentGPT#12]
When the agent is done , can it give a downloadable text file or pdf with the data from the agent that contains it's findings.

**Comment by alreadydone** [comment]
Related: currently I can copy the whole output but I think the "(Restart if this takes more than 30 seconds)" message could be omitted (made un-copiable), and there should be a space after `:`, e.g. `Added task: `.

**Comment by mrayonnaise** [comment]
Some progress towards this in [this PR](https://github.com/reworkd/AgentGPT/pull/27) but it does not perform any filtering.

**Comment by asim-shrestha** [comment]
Thanks @mrayonnaise, closing
