### ISSUE TITLE
issue with installation not opening once installed

### ISSUE THREAD

**Issue by DMTarmey** [reworkd/AgentGPT#121]
Hi i installed the software but it doesn't start, how can i troubleshoot it can i used vs

**Comment by exilvm** [comment]
Sorry, but without more specific information such as error messages or steps to reproduce the issue, I'm unable to provide further troubleshooting assistance.

**Comment by DMTarmey** [comment]
so in installed the code on windows 11 and when i click on new shortcut button to open it it did nothing ? Are you also working as freelance engineer can you install this on my machine for a fee ?

**Comment by DMTarmey** [comment]
so in installed the code on windows 11 and when i click on new shortcut button to open it it did nothing ?

**Comment by DMTarmey** [comment]
so in installed the code on windows 11 and when i click on new shortcut button to open it it did nothink ?
