### ISSUE TITLE
Login failes: reworkd_platform.User.super_admin does not exist

### ISSUE THREAD

**Issue by liferadioat** [reworkd/AgentGPT#1219]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

Login at development mode should work as expected

### Current behaviour

An error occurs. Docker logs says:
```
prisma:error
Invalid `p.user.findUnique()` invocation in
/next/node_modules/@next-auth/prisma-adapter/dist/index.js:210:43

  207 return {
  208     createUser: (data) => p.user.create({ data }),
  209     getUser: (id) => p.user.findUnique({ where: { id } }),
→ 210     getUserByEmail: (email) => p.user.findUnique(
The column `reworkd_platform.User.super_admin` does not exist in the current database.
prisma:query SELECT `reworkd_platform`.`User`.`id`, `reworkd_platform`.`User`.`name`, `reworkd_platform`.`User`.`email`, `reworkd_platform`.`User`.`emailVerified`, `reworkd_platform`.`User`.`image`, `reworkd_platform`.`User`.`super_admin`, `reworkd_platform`.`User`.`createDate` FROM `reworkd_platform`.`User` WHERE (`reworkd_platform`.`User`.`email` = ? AND 1=1) LIMIT ? OFFSET ?
```

### Steps to reproduce

install agentgpt with docker compose by docker compose  up --build -d and use NODE_ENV=development as .env parameter

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by clickbrain** [comment]
Having the same issue. Go to the localhost. Enter a name/goal and it asks me to login. I am given a page to login, but no indication of how to create a user or login. There's a checkbox with Admin. Can find zero documentation on this process or how to crate a user. No matter what I put in the login field (Admin, a name, an email address, etc) I get a 404 error on localhost. 

   | prisma:query SELECT 1
next                 | prisma:query SELECT `reworkd_platform`.`User`.`id`, `reworkd_platform`.`User`.`name`, `reworkd_platform`.`User`.`email`, `reworkd_platform`.`User`.`emailVerified`, `reworkd_platform`.`User`.`image`, `reworkd_platform`.`User`.`super_admin`, `reworkd_platform`.`User`.`createDate` FROM `reworkd_platform`.`User` WHERE (`reworkd_platform`.`User`.`email` = ? AND 1=1) LIMIT ? OFFSET ?
next                 | prisma:error 
next                 | Invalid `p.user.findUnique()` invocation in
next                 | /next/node_modules/@next-auth/prisma-adapter/dist/index.js:210:43
next                 | 
next                 |   207 return {
next                 |   208     createUser: (data) => p.user.create({ data }),
next                 |   209     getUser: (id) => p.user.findUnique({ where: { id } }),
next                 | → 210     getUserByEmail: (email) => p.user.findUnique(
next                 | The column `reworkd_platform.User.super_admin` does not exist in the current database.

**Comment by jasangill1** [comment]
Hello @clickbrain Try deleting your docker volume and rebuilding via docker compose build !!!

**Comment by KennyDizi** [comment]
@jasangill1 I got the same problem even I deleted all Docker cached => rebuild with Docker compose.
jFYI even upgraded prisma to v5 doesn't help.

**Comment by liferadioat** [comment]
After deleting volume agentgpt_db_data and rebuild the project everything works again.

**Comment by jasangill1** [comment]
@KennyDizi delete the docker volume not just the cache there's a tab on the left side that says volume! Let me know if this resolves the issue!!!

**Comment by asim-shrestha** [comment]
@liferadioat @KennyDizi @clickbrain thanks for the help here! Have since removed mentions of this so should be good to go with a new docker build!
