### ISSUE TITLE
Unexpected Token Error when running setup.sh

### ISSUE THREAD

**Issue by ericthegeek** [reworkd/AgentGPT#1243]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

Expecting setup.sh to run successfully and complete setup.

### Current behaviour

When running setup.sh I get this error:
file:///root/Dev/AgentGPT/cli/node_modules/inquirer/lib/prompts/editor.js:78
      postfix: this.opt.postfix ?? '.txt',
                                 ^

SyntaxError: Unexpected token '?'

### Steps to reproduce

I am running on Ubuntu 22.04
I am simply cloning the repo and running the setup.sh file as described in the docs.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Surasia** [comment]
Ubuntu's apt repo uses an old version of node (v12.22.9) which has not yet implemented the **nullish coalescing (??)** operator which was added in nodeJS v14.

To fix this; you can use NVM:

### Install NVM
`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash`

(restart your terminal to finish installation)

### Run NVM and update Node

Latest: `nvm install node`
LTS: `nvm install -lts`

### Select new node version

First, list the node versions using `nvm ls`, then you can use the version you want using `nvm use <version>`. For LTS, use `nvm use --lts`.

Lastly, make sure you update npm using `npm install -g npm`. Hope I could help :)

**Comment by asim-shrestha** [comment]
Thanks @Surasia
