### ISSUE TITLE
Has this project been published on Docker Hub?

### ISSUE THREAD

**Issue by Passerby1011** [reworkd/AgentGPT#125]
Has this project been published on Docker Hub?
I want to deploy it on my NAS, and it would be much easier if it has been published on Docker Hub.

**Comment by awtkns** [comment]
Not yet, this is something we can get done soon hopefully!

**Comment by theend777** [comment]
Would 

> Not yet, this is something we can get done soon hopefully!

Would you consider to support it in railway.app by the way?

**Comment by exilvm** [comment]
> Not yet, this is something we can get done soon hopefully!

I do plan to work on a Github Actions workflow that builds the image and publishes it to the Github Container registry.

Personally, I would recommend using the GitHub Container Registry over Dockerhub as it offers easier integration.

**Comment by awtkns** [comment]
Github would be even better! We can likely support both in the future. Ty @exilvm

**Comment by xinmans** [comment]
we need pull image from docker hub, coz failure when build from setup.sh --docker, it's so sad

**Comment by DMTarmey** [comment]
I tried to install this project with docker which is included in the code, when i was messing around trying to understand what each part did I ran debugger and it said docker was including in the package but hadn't been installed, it ask if I wanted to install it an di said yes, worst mistake of my life the docker stopped win1  from starting and after hours of troubleshooting I ended up restoring windows.

**Comment by awtkns** [comment]
This project has not been shared on docker hub yet unfortunately. I'm sorry to hear that about your windows!

**Comment by awtkns** [comment]
This project has not been shared on docker hub yet unfortunately. I'm sorry to hear that about your windows!

**Comment by asim-shrestha** [comment]
Hey @exilvm, we've since update our docker compose so this may be a touch outdated now. Would love to see all of that in a draft PR and we can evaluate further. Thanks for the help!

**Comment by exilvm** [comment]
> Hey @exilvm, we've since update our docker compose so this may be a touch outdated now. Would love to see all of that in a draft PR and we can evaluate further. Thanks for the help!
Hello! I'm not updated with the recent changes in the project so my draft PR is probably outdated. I was not able to find any free time to work on it (or maintain any of my side projects) due to my final year exams. I'm still planning to continue working on it though. Thanks.
