### ISSUE TITLE
Max loops of 26 exceeded, shutting down.

### ISSUE THREAD

**Issue by Flom95** [reworkd/AgentGPT#1252]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

Hey team, I have subscribed the pro version and for each request, after executing taks, it is stopped w/ the same message : "Max loops of 26 exceeded, shutting down."
Could you please help?
Thks

### Current behaviour

Any request, same stops...

### Steps to reproduce

Any request, same stops...

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by jasangill1** [comment]
Hello @Flom95 Would you expand on this so does it say max loops after just one loop has gone by?

**Comment by asim-shrestha** [comment]
Heyo! We've removed the notion of looping. Closing :)

**Comment by dehness** [comment]
I experience the same problem. It completes 26 loops and then shuts down. It can never seem to create anything or answer anything before the 26 loops are up and I can't seem to find any way to have it continue from where it left off. The only options are Back, Delete, and Share.
