### ISSUE TITLE
Have you considered introducing New Bing?

### ISSUE THREAD

**Issue by Passerby1011** [reworkd/AgentGPT#127]
New Bing uses GPT-4 to preprocess the content of search results. Would using it as a source of information have better results? Additionally, if New Bing is used as part of the sources of information, would it potentially save on API expenses since it's a free service? Have you considered using New Bing?

**Comment by debater-coder** [comment]
This would be difficult, as the 'new bing' does not have an API. If a project as large as this tried to use it through non-official means it would likely get patched.

**Comment by jasangill1** [comment]
Hello @Passerby1011 @debater-coder will be closing as the question has been answered if you would still need more clarification feel free to reopen!!!
