### ISSUE TITLE
The agent indicates that he has finished the tasks without having started any of them.

### ISSUE THREAD

**Issue by brooeas** [reworkd/AgentGPT#129]
I have tried giving it a prompt which worked yesterday but now it finishes the tasks directly. Do you know what I might be doing wrong?

![image](https://user-images.githubusercontent.com/47078652/232092148-daf06be2-9761-4f4f-9cc2-8d292e1f407d.png)
![image](https://user-images.githubusercontent.com/47078652/232092199-26d071f4-4ff7-4fc8-b563-4ccf04d613e9.png)

I am using the same configuration yesterday worked

**Comment by asim-shrestha** [comment]
Hey, we updated our prompt configuration and this seems to have caused an issue when you request for a list. We've reverted this

![image](https://user-images.githubusercontent.com/50181239/232181404-d41c4c79-9579-4896-b8d7-8a4de5507d81.png)

**Comment by yourepicservices** [comment]
Hi, @rogarvi2. Please let us know if you need further help or if the reverted prompt configuration mentioned above helped.
