### ISSUE TITLE
copy button

### ISSUE THREAD

**Issue by louis030195** [reworkd/AgentGPT#1311]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/reworkd/AgentGPT/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/reworkd/AgentGPT/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

copy button

### ✔️ Solution

<img width="212" alt="image" src="https://github.com/reworkd/AgentGPT/assets/25003283/070b96a9-6d5d-41d4-befd-1496660b15f6">

<img width="351" alt="image" src="https://github.com/reworkd/AgentGPT/assets/25003283/39b295ef-ede2-4be9-9690-5dc356aad793">

### ❓ Alternatives

not using agentgpt

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by asim-shrestha** [comment]
![image](https://github.com/reworkd/AgentGPT/assets/50181239/4e07adbe-a936-4170-808b-93044e01305b)

Hey currently there is already a copy button at the top right, is this what you're looking for?
