### ISSUE TITLE
Localhost Install not connecting to server

### ISSUE THREAD

**Issue by brown7477** [reworkd/AgentGPT#1321]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

I was expecting Agents to be created and solve the task but I am getting errors

### Current behaviour

![AgentGPT](https://github.com/reworkd/AgentGPT/assets/24249276/5b445154-3309-4948-90fd-0f22bbafb7d1)

### Steps to reproduce

Install Platform choosing Docker install
Setup as required.
Run App

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by itsanishjain** [comment]
Yeah getting this same error

![image](https://github.com/reworkd/AgentGPT/assets/43033153/dafde7c0-a28a-45af-b8bf-a9f3cc95c265)

There is call to this endpoint

http://localhost:8000/api/agent/tools

and it's failing

tried this as well but no success

https://github.com/reworkd/AgentGPT/issues/1303

**Comment by asim-shrestha** [comment]
Hey folks! Please run through docker and try again. Should be good to go now :)
