### ISSUE TITLE
Platform Container Fails to Allow Selection of GPT-4 Due to Missing httpx Python Module

### ISSUE THREAD

**Issue by kazin-kharizma** [reworkd/AgentGPT#1323]
---

**Issue**: Platform Container Fails to Allow Selection of GPT-4 Due to Missing `httpx` Python Module

**Expected Behavior**: 
The platform container should start without any errors. Upon confirming your API key, the dropdown selector should allow you to choose between different models like gpt-3.5, gpt-3.5-turbo, and gpt-4. All required Python modules should be installed during the container build process.

**Current Behavior**: 
The container starts and http://localhost:3000 comes up, but the dropdown selector for choosing between models is non-functional. Fresh installs do not resolve the issue. Additionally, a `ModuleNotFoundError` for 'httpx' may appear, indicating not all features will be operational.

**Steps to Reproduce**:

```bash
# Clone the AgentGPT repository and navigate to the project directory
git clone https://github.com/reworkd/AgentGPT.git
cd AgentGPT

# Run the setup script and follow the prompts
./setup.sh

# Open localhost and try to change your model settings
Open https://localhost:3000
```

**Troubleshooting Steps Taken**:

- Checked the Dockerfile for the platform container.
- Noticed the project uses Poetry for Python dependency management.
- Realized `httpx` was not listed in `pyproject.toml` under `[dependencies]`, despite being required for full functionality.

**Solution**: 
Add `httpx = "^0.24.1"` to the `[dependencies]` section of `pyproject.toml`.

**Steps to Implement Solution**:

```bash
# Open pyproject.toml and add the following line under [dependencies]
httpx = "^0.24.1"

# Rebuild the platform container
docker-compose build platform

# Restart the Docker services
docker-compose down
docker-compose up -d
```

**Additional Information**: 
The project uses Poetry for Python dependency management. The Dockerfile specifies `python:3.11-slim-buster` as the base image.

**Operating Systems Affected**:
- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

**Acknowledgements**:
- [X] Issue title is concise, descriptive, and in title casing.
- [X] Searched existing issues to ensure this has not been reported yet.
- [X] Using the latest version of AgentGPT.
- [X] Provided enough information for maintainers to reproduce and diagnose the issue.

---

Feel free to copy-paste this into your GitHub issue. It should align well with the format you're aiming for. 🧐

**Comment by kazin-kharizma** [comment]
**Issue**: Platform Container Fails to Allow Selection of GPT-4 Due to Missing httpx Python Module

**Solution**: Add `httpx` to the dependencies in the `pyproject.toml` file.

**Steps to Implement Solution**:

1. Open `pyproject.toml`.
2. Add `httpx = "^0.24.1"` under `[dependencies]`.
3. Rebuild the platform container using `docker-compose build platform`.
4. Restart the Docker services using `docker-compose down` and `docker-compose up -d`.

```bash
# Open pyproject.toml and add the following line under [dependencies]
httpx = "^0.24.1"

# Rebuild the platform container
docker-compose build platform

# Restart the Docker services
docker-compose down
docker-compose up -d
```

**Additional Information**: The project uses Poetry for Python dependency management and the Dockerfile uses `python:3.11-slim-buster` as the base image.

This solution should help others who encounter the same issue.
----------------------

**Comment by asim-shrestha** [comment]
Hey @kazin-kharizma, this should be fixed now! Thanks for the report.

**Comment by cranyy** [comment]
This issue seems to still persist even after fix. I cant select anything other than gpt 3.5. there is no dropdown option
