### ISSUE TITLE
Outdated Twitter Logo

### ISSUE THREAD

**Issue by Yash-Ambekar** [reworkd/AgentGPT#1330]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/reworkd/AgentGPT/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/reworkd/AgentGPT/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

The twitter logo on main page is outdated. It should be the `X` logo.
![image](https://github.com/reworkd/AgentGPT/assets/96481913/68263182-839e-4a80-ae32-0d6825b981ae)

### ✔️ Solution

Replace the outdated Twitter logo with the updated one.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by sohamtembhurne** [comment]
I have started work on this issue. I will raise a pull request.
