### ISSUE TITLE
Docker build fail

### ISSUE THREAD

**Issue by rossman22590** [reworkd/AgentGPT#1334]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

it installs via docker

### Current behaviour

 [platform prod  2/10] RUN apt-get update && apt-get install -y   default-libmysqlclient-dev   gcc   pkg-config   openjdk-11-jdk   build-essential   && rm -rf /var/lib/apt/lists/*:
0.495 Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
0.595 Err:1 http://deb.debian.org/debian buster InRelease
0.595   At least one invalid signature was encountered.
0.633 Get:2 http://deb.debian.org/debian-security buster/updates InRelease [34.8 kB]
0.674 Err:2 http://deb.debian.org/debian-security buster/updates InRelease
0.674   At least one invalid signature was encountered.
0.730 Get:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
0.806 Err:3 http://deb.debian.org/debian buster-updates InRelease
0.806   At least one invalid signature was encountered.
0.808 Reading package lists...
0.812 W: GPG error: http://deb.debian.org/debian buster InRelease: At least one invalid signature was encountered.
0.812 E: The repository 'http://deb.debian.org/debian buster InRelease' is not signed.
0.812 W: GPG error: http://deb.debian.org/debian-security buster/updates InRelease: At least one invalid signature was encountered.
0.812 E: The repository 'http://deb.debian.org/debian-security buster/updates InRelease' is not signed.
0.812 W: GPG error: http://deb.debian.org/debian buster-updates InRelease: At least one invalid signature was encountered.
0.812 E: The repository 'http://deb.debian.org/debian buster-updates InRelease' is not signed.       
------
failed to solve: process "/bin/sh -c apt-get update && apt-get install -y   default-libmysqlclient-dev   gcc   pkg-config   openjdk-11-jdk   build-essential   && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

### Steps to reproduce

setup.bat

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by rossman22590** [comment]
found 0 vulnerabilities
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Ross\Desktop\agentgpt\AgentGPT\package.json
npm ERR! errno -4058
npm ERR! enoent Could not read package.json: Error: ENOENT: no such file or directory, open 'C:\Users\Ross\Desktop\agentgpt\AgentGPT\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\Ross\AppData\Local\npm-cache\_logs\2023-10-21T04_24_24_003Z-debug-0.log

**Comment by sakdakom** [comment]
https://github.com/reworkd/AgentGPT/issues/1334#issuecomment-1773655673

**Comment by asim-shrestha** [comment]
Hey folks, should be good now! Thanks for the report
