### ISSUE TITLE
There was an unexpected issue getting a response from the AI model.

### ISSUE THREAD

**Issue by Tobylamb** [reworkd/AgentGPT#1448]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

After I set the goal, the agent should think and give the result,.

### Current behaviour

But it shows an error after thinking: There was an unexpected issue getting a response from the AI model.
![issue](https://github.com/reworkd/AgentGPT/assets/140294675/0638e63c-fc41-4833-8630-4c79622125b3)

### Steps to reproduce

I just followed the official process to deploy locally and made no other changes:
git clone https://github.com/reworkd/AgentGPT.git
cd AgentGPT
./setup.bat

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Tobylamb** [comment]
See similar problem, but still not solved

**Comment by tobecrazy** [comment]
+1
