### ISSUE TITLE
Please kindly support OPENAI_BASE_URL in configuration

### ISSUE THREAD

**Issue by chrischjh** [reworkd/AgentGPT#149]
Please kindly support OPENAI_BASE_URL in .env options, thanks a lot

**Comment by yourepicservices** [comment]
Similar to #90

**Comment by asim-shrestha** [comment]
Added support for custom base url: https://github.com/reworkd/AgentGPT/pull/543

Going to close this as a result. I'll also include something in the documentation to describe this
