### ISSUE TITLE
I get always this error?? what to do??

### ISSUE THREAD

**Issue by Dennis19931503** [reworkd/AgentGPT#150]
ERROR retrieving initial tasks array. Make sure your API key is not the free tier, make your goal more clear, or revise your goal such that it is within our model's policies to run. Shutting Down.

I set up an API. I am so to speak the free tier but I still have the free credits?

What am i Doing wrong?

**Comment by kekechain** [comment]
I am meeting the same problem.

**Comment by mmctotheAZ** [comment]
I have paid and I'm getting the same error - ERROR retrieving initial tasks array. Make sure your API key is not the free tier, make your goal more clear, or revise your goal such that it is within our model's policies to run. Shutting Down.

**Comment by yourepicservices** [comment]
Created #162 to help with key validation, this seems to be a common confusion.

**Comment by yourepicservices** [comment]
Have you insured to include the "sk-" at the beginning of the key?

**Comment by drobins81** [comment]
Dear Support Team,

I have recently encountered a recurring error message that seems to be a common issue among users. Despite having both a paid ChatGPT Plus account and a paid OpenAI API account, which has granted me access to an API key, I am still experiencing this problem.

I kindly request your assistance in resolving this issue as soon as possible. Your prompt support would be greatly appreciated.

Thank you in advance for your help.

Sincerely,
Dominick

**Comment by Fai1edMit0sis** [comment]
Same thing for me too.

**Comment by sevenguin** [comment]
may be, it's just avalible for paid account.

**Comment by savethehousemouse** [comment]
it seems to have started in the afternoon of 15.Apr.2023. I could run a test session before.

**Comment by savethehousemouse** [comment]
using Codespace and used brandspanking new api key. Same result

**Comment by Budman17r** [comment]
seems to be related to the chatgpt4, chatgpt 3.5 turbo is working, well appears to be.

**Comment by savethehousemouse** [comment]
installed locally and it works on 3.5 with key.

**Comment by asim-shrestha** [comment]
Hey folks, closing now because we've added validation, updated messaging, and provided an FAQ for common API key issues.
