### ISSUE TITLE
Suddenly stop in the middle of the browser running and report an error.

### ISSUE THREAD

**Issue by 740371467** [reworkd/AgentGPT#154]
There is only one sentence in the whole browser interface：
Application error: a client-side exception has occurred (see the browser console for more information).

**Comment by exilvm** [comment]
To troubleshoot the issue, we need to see the error in the console log.

**Comment by yourepicservices** [comment]
Possibly related to #123

**Comment by asim-shrestha** [comment]
Going to close in favor of that ticket
