### ISSUE TITLE
Support for Local LLMs via Ollama

### ISSUE THREAD

**Issue by zanderlewis** [reworkd/AgentGPT#1560]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/reworkd/AgentGPT/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/reworkd/AgentGPT/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Local LLMs through Ollama would allow for free use of AgentGPT.

### ✔️ Solution

Support for Local LLMs using [Ollama](https://github.com/ollama/ollama)

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by jayzalani** [comment]
Ig using the Ollama will suit better more specifically the newer version with more capacity but would liked to coined some alternatives such as https://python.langchain.com/v0.1/docs/guides/development/local_llms/ as it is more Flexible
