### ISSUE TITLE
NEXTAUTH_SECRET is not working

### ISSUE THREAD

**Issue by xiaosaaaa** [reworkd/AgentGPT#157]
Why is the “NEXTAUTH_SECRET” I set in .env not working, but the “OPENAI_API_KEY” I set is working?

**Comment by exilvm** [comment]
Why not just run `./setup.sh`? it should take care of setting those values.

Check the [Getting Started](https://github.com/reworkd/AgentGPT#-getting-started) section if you haven't already.

**Comment by xiaosaaaa** [comment]
The problem still arises

**Comment by yourepicservices** [comment]
@xiaosaaaa, can you please be more specific on what's not working. Are you getting a specific error message? What steps are you taking to produce the issue?

**Comment by xiaosaaaa** [comment]
I am starting the project using either "npm run dev" or "./setup.sh". "NEXTAUTH_SECRET" is used to prevent the project API from being quickly consumed when it is placed on the public network. I have already set up "NEXTAUTH_SECRET" and "OPENAI_API_KEY", but now the project runs normally without the need for me to input the previously set "NEXTAUTH_SECRET",and there is no error message displayed.  If I leave "OPENAI_API_KEY" empty by default, the project can't run normally .So I say "NEXTAUTH_SECRET" I set in .env is not working, but the "OPENAI_API_KEY" I set is working.

**Comment by seefelder** [comment]
error - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 0
    at new NodeError (node:internal/errors:399:5)

**Comment by yourepicservices** [comment]
@seefelder I think #90 is related, seems like a regional issue.

**Comment by alorbach** [comment]
How to debug this ERR_HTTP_INVALID_STATUS_CODE error?

**Comment by asim-shrestha** [comment]
Going to delete due to inactivity. Seems to be addressed in https://github.com/reworkd/AgentGPT/issues/90
