### ISSUE TITLE
[ENHANCEMENT]- title of website isnt properly visible

### ISSUE THREAD

**Issue by abhinav2712** [reworkd/AgentGPT#16]
I am aware that this is a beta version, however the website title seems off:
![image](https://user-images.githubusercontent.com/68495520/231154140-56e15983-7cc1-492e-a413-84c46b1114b2.png)

Assign me this issue, I will fix it and we will be done with these types of trivial issues in no time..

**Comment by awtkns** [comment]
@abhinav2712 any contributions are more then welcome! 🎉

**Comment by abhinav2712** [comment]
@awtkns May I know the source for the website's files? I just downloaded the software in my system but I cant find files for the website

**Comment by prathamjagga** [comment]
What do you mean by the source of website files and which software are you talking about?

**Comment by asim-shrestha** [comment]
Will be handled in #22, closing

**Comment by asim-shrestha** [comment]
@abhinav2712 this is a next js project, refer to the READMe here to get started or look into NextJS documentation
