### ISSUE TITLE
[Enhancement] Add API key validation

### ISSUE THREAD

**Issue by yourepicservices** [reworkd/AgentGPT#162]
**Problem**
Users seem to have a hard time with OpenAI API keys working, improperly inputting API keys, or obtaining the proper subscription.

**Suggested Solution(s)**
The following would provide more clear instruction and error handling to make API keys more intuitive.
- [x] Add more clear instructions for setting up the OpenAI API key and obtaining the payment/subscription requirements.
- [x] Modify the setup.sh process to include regex key validation. Example: ^sk-[a-zA-Z0-9]{40}$
- [x] Add field validation to the settings menu
- [x] Add key validation by doing a test call after the key is provided

**Comment by hemangjoshi37a** [comment]
Hi, 

To solve this issue, we can follow the suggested solutions mentioned in the issue description:

1. Add more clear instructions for setting up the OpenAI API key and obtaining the payment/subscription requirements.

2. Modify the setup.sh process to include regex key validation. Example: ^sk-[a-zA-Z0-9]{40}$

3. Add field validation to the settings menu

4. Add key validation by doing a test call after the key is provided

By implementing these solutions, we can make the API key validation more intuitive and error-free for the users. Let me know if you have any questions or concerns.

**Comment by matthope1** [comment]
I can work on this tonight. 
@yourepicservices do you know if the open API key uses a standard I can reference for the validation?

**Comment by asim-shrestha** [comment]
Awesome! I think that Regex might do the trick

Updated error message based on actually calling the API last night so at least that's out of the way already

**Comment by matthope1** [comment]
@asim-shrestha, 

I covered these two [here](https://github.com/reworkd/AgentGPT/pull/219)

1. Modify the setup.sh process to include regex key validation.
2. Add field validation to the settings menu

**Comment by asim-shrestha** [comment]
Nice! Just ` Add more clear instructions for setting up the OpenAI API key and obtaining the payment/subscription requirements.` left then
