### ISSUE TITLE
I keep getting an error message with AgentGPT

### ISSUE THREAD

**Issue by drobins81** [reworkd/AgentGPT#164]
Dear Support Team,

I have recently encountered a recurring error message that seems to be a common issue among users. Despite having both a paid ChatGPT Plus account and a paid OpenAI API account, which has granted me access to an API key, I am still experiencing this problem.

I kindly request your assistance in resolving this issue as soon as possible. Your prompt support would be greatly appreciated.

Thank you in advance for your help.

Sincerely,
Dominick

**Comment by yourepicservices** [comment]
#162

**Comment by asim-shrestha** [comment]
Hey we've updated our error messaging, most likely your API count needs to associate a credit card to it. Closing now but feel free to reach out if anything else arises
