### ISSUE TITLE
You crazy scammer kids may wanna ditch this guy

### ISSUE THREAD

**Issue by TheRealMiRRoRMaN** [reworkd/AgentGPT#1654]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

https://github.com/OneB1ank

He sorta screws up, I mean after he tried to hack my phone with a clever hack it was pretty easy to find out who he was. 

https://www.youtube.com/channel/UCrmJAoHmmzeWm3_eVjJ8qpg/videos

But hey, good luck trying to make a dishonest buck, kids. 

### Current behaviour

yeah. 

### Steps to reproduce

use his clever little A1 magisk module that has a trojan apk in it. 

### Possible solution

find honest jobs, "hackers" I mean i seen your whole team this entire enterprise is screwed from the get go.

### Which Operating Systems are you using?

- [X] Android
- [X] iPhone/iPad
- [X] Linux
- [X] macOS
- [X] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by awtkns** [comment]
Thanks for the report. We will take a look :)
