### ISSUE TITLE
Chineese not supported - 不支持中文话题啊

### ISSUE THREAD

**Issue by vehome** [reworkd/AgentGPT#177]

**Comment by vastxie** [comment]
https://agentgpt.vast123.com/
汉化了下，可以试试。

**Comment by a506488043** [comment]
@vastxie 你是怎么部署的？应该不是docker吧

**Comment by hemangjoshi37a** [comment]
Hi @vehome, 

It seems like you haven't provided any description of the issue you are facing. Can you please provide more details about the problem you are encountering so that we can assist you better? 

Thank you.

**Comment by Lone333** [comment]
> https://agentgpt.vast123.com/
> 汉化了下，可以试试。

可否共享下，谢谢

**Comment by vastxie** [comment]
> @vastxie 你是怎么部署的？应该不是docker吧

npm run dev

**Comment by vastxie** [comment]
> > https://agentgpt.vast123.com/
> > 汉化了下，可以试试。
> 
> 可否共享下，谢谢

主要是修改 src/utils/chains  中的内容，晚点儿拉个fork

**Comment by Lone333** [comment]
> > > https://agentgpt.vast123.com/
> > > 汉化了下，可以试试。
> > 
> > 
> > 可否共享下，谢谢
> 
> 主要是修改 src/utils/chains 中的内容，晚点儿拉个fork

多谢啦，这边部署vercel时总是报环境变量错误，不知道你那里怎么解决的呢？

**Comment by awtkns** [comment]
@Jshen123 would you be able to help here. I think i saw you responding to another thread in Chinese. It would be great if we could bring chineese support on to the platform

**Comment by awtkns** [comment]
@vastxie would you be intrested in bringing these changes to the main repo?

**Comment by a506488043** [comment]
@vastxie 
用npm run dev报各种错误。搭建不起来

**Comment by Jshen123** [comment]
@vehome  AgentGPT 支持中文话题但是所有的回复还是英文。 
@vastxie 欢迎你帮助我们开发中文支持 :smile:

**Comment by vastxie** [comment]
> @vastxie would you be intrested in bringing these changes to the main repo?

I am happy to do this, I will submit my code later.

**Comment by adminlove520** [comment]
> > > > https://agentgpt.vast123.com/
> > > > 汉化了下，可以试试。
> > > 
> > > 
> > > 可否共享下，谢谢
> > 
> > 
> > 主要是修改 src/utils/chains 中的内容，晚点儿拉个fork
> 
> 多谢啦，这边部署vercel时总是报环境变量错误，不知道你那里怎么解决的呢？

我这边也是环境变量报错  但是本地dev正常
![image](https://user-images.githubusercontent.com/32920883/232421604-b4d7c6a1-2f3b-4848-ace8-a55b002c3d16.png)

**Comment by yuntao1997** [comment]
我刚试了一下，将prompt改成中文， 返回的结果就都是中文了

**Comment by adminlove520** [comment]
> 我刚试了一下，将prompt改成中文， 返回的结果就都是中文了
> 
> ![image](https://user-images.githubusercontent.com/24284389/232437775-a10cf679-2740-472d-a64a-1373e971f8c3.png)

界面的语言怎么调整呀

**Comment by adminlove520** [comment]
> @vastxie 用npm run dev报各种错误。搭建不起来

这是因为你没有配置环境变量  需要配置一下呢

**Comment by adminlove520** [comment]
能否引用i18n呀

**Comment by yuntao1997** [comment]
主要改一下这几个文件就好了，引用i18n我觉得没问题，我弄一下试试。 

prompt：src/utils/chain.ts、src/components/ChatWindow.tsx
页面：src/pages/index.tsx

**Comment by yuntao1997** [comment]
算了，我选择放弃，ts、react都不怎么熟，写死还行，动态的。。  交给其他大佬来。。

**Comment by vastxie** [comment]
> 算了，我选择放弃，ts、react都不怎么熟，写死还行，动态的。。  交给其他大佬来。。

需要改的文本不怎么多，可以在index页面中设置下拉框选择语言全局切换，这样就不涉及插件路由什么的。晚点儿来实现下

**Comment by microcodor** [comment]
简单汉化了下，核心是在预添加的前置提示词，指定回复的答案要和提问的语言类型一致，就可以实现用户用什么语言提问，回答就用什么语言回答。
网站内容简单翻译了下。
生成PDF的时候会有乱码，换了一个中文的字体库。
已经部署在vercel上，部署的时候注意next.config.mjs下的这行代码可以注释掉：
//!process.env.SKIP_ENV_VALIDATION && (await import("./src/env/server.mjs"));
做了个demo，大家可以看看：
[AgentGPT汉化版](https://agentgpt.jinchun.vip)
[代码地址](https://github.com/microcodor/ZhAgentGPT)

**Comment by yuntao1997** [comment]
大佬集成下i18n，提交到主分支呗，后面升级方便

**Comment by Jshen123** [comment]
> 大佬集成下i18n，提交到主分支呗，后面升级方便
好的，这个星期内集成i18n 🙏

**Comment by Jshen123** [comment]
PR for i18n implementation
https://github.com/reworkd/AgentGPT/pull/270

**Comment by Cs4K1Sr4C** [comment]
It's coming, but still pending on approval...

**Comment by asim-shrestha** [comment]
Implemented!
