### ISSUE TITLE
sh: 1: next: not found

### ISSUE THREAD

**Issue by a506488043** [reworkd/AgentGPT#179]
But I reported an error when executing npm run dev
```
> agent-gpt@0.1.0 dev
> next dev

sh: 1: next: not found
```
![image](https://user-images.githubusercontent.com/16434125/232309968-48074cea-a5e2-4774-99cb-d1bd2d79d50b.png)

system configuration：Linux ITX 5.19.0-40-generic #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yourepicservices** [comment]
Try npm install again maybe, sounds like dependencies aren't installed.

**Comment by a506488043** [comment]
```
npm ERR! code 1
npm ERR! path /mnt/256G/docker/AgentGPT/node_modules/prisma
npm ERR! command failed
npm ERR! command sh -c node scripts/preinstall-entry.js
npm ERR! ┌─┐
npm ERR! │   …│
npm ERR! └┘

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-04-16T13_54_31_166Z-debug-0.log
```
![image](https://user-images.githubusercontent.com/16434125/232316139-f4bbac18-343d-4fb6-8820-e45532829b96.png)
@yourepicservices

**Comment by a506488043** [comment]
```
npm ERR! Missing script: "dev"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-04-16T14_13_54_083Z-debug-0.log
```

**Comment by a506488043** [comment]
```
27 timing npm:load Completed in 10ms
28 silly logfile start cleaning logs, removing 1 files
29 timing command:run Completed in 2ms
30 verbose stack Error: Missing script: "dev"
30 verbose stack
30 verbose stack To see a list of scripts, run:
30 verbose stack   npm run
30 verbose stack     at RunScript.run (/usr/share/nodejs/npm/lib/commands/run-script.js:95:13)
30 verbose stack     at async module.exports (/usr/share/nodejs/npm/lib/cli.js:66:5
```

**Comment by yourepicservices** [comment]
Looks to me like you need to update nodejs, assuming that's the engine it's referring to.
![image](https://user-images.githubusercontent.com/38015040/232345150-ae746730-f368-457c-be5a-903edda12896.png)

**Comment by ankit-akd** [comment]
Even I get the same error whenever I try to do 'npm install'(all the dependencies are latest)
Sometimes I get the issue as "pngquant not installed" but getting error while installing that too.
Any help would be appreciated

**Comment by asim-shrestha** [comment]
Have you updated your node version ?

**Comment by Amosi-04-sanga** [comment]
understood

**Comment by QinHsiu** [comment]
I run the following command: num=os.system("cat test.txt | wc -l") 

, and face the problem too, sh: 1: 224400: not found
