### ISSUE TITLE
📝 Ability to save entire runs as a PDF / Text

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#18]
Currently, we have the option of saving the run as an image. This is good for sharability but not effective in actually using output from the tool. The save button should open up a dialog that allows the user to either download the image, download a pdf/text document, or save the conversation to the clipboard

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/50181239/231246381-92ed7edc-5e0a-492d-a5f3-b6f6d1ff64f1.png">

**Comment by JBic9832** [comment]
I have been looking into this issue and it would seem that the copy text feature could be put together with a library like reactPDF to turn the text into a PDF. The downside to this approach is needing to stylize the PDF manually as I do not believe it does so automatically.

**Comment by psgit** [comment]
> I just noticed the original description of this mentions a popup for saving. I added a dropdown and psgit added a button, would we prefer buttons, dropdown, or a popup?

I think that the Download PDF button functionality could be easily added to a dropdown or popup, if that is where the other save options are going to be.

**Comment by asim-shrestha** [comment]
Thanks @psgit and @yourepicservices! Looks like we have a dropdown with individual buttons for the different saving modalities. Appreciate the help and direction - Closing
