### ISSUE TITLE
How to set up an anti-generation using other APIs

### ISSUE THREAD

**Issue by Mgrsc** [reworkd/AgentGPT#196]
Is it possible to set API_REVERSE_PROXY to set the reverse proxy, there are restrictions in my region, so I can't use api directly

**Comment by asim-shrestha** [comment]
Duplicate of #175 and #36. Closing

**Comment by asim-shrestha** [comment]
Added support for custom base url for local development: https://github.com/reworkd/AgentGPT/pull/543

I'll also include something in the documentation to describe this
