### ISSUE TITLE
Build Failing on Prisma parameters

### ISSUE THREAD

**Issue by 9darksider9** [reworkd/AgentGPT#209]
Got the below error when trying to deploy locally:

`=> ERROR [7/8] RUN npx prisma generate      && npx prisma migrate dev --  1.4s
------                                                                          
 > [7/8] RUN npx prisma generate      && npx prisma migrate dev --name init      && npx prisma db push:
#12 1.177 Environment variables loaded from .env
#12 1.179 Prisma schema loaded from prisma/schema.prisma
#12 1.300 warn Preview feature "ReferentialIntegrity" is deprecated. The functionality can be used without specifying it as a preview feature.
#12 1.304 Error: Prisma schema validation - (get-dmmf wasm)
#12 1.304 Error code: P1012
#12 1.304 error: Error validating: You defined the enum `Role`. But the current connector does not support enums.
#12 1.304   -->  schema.prisma:12
#12 1.304    | 
#12 1.304 11 | 
#12 1.304 12 | enum Role {
#12 1.304 13 |   ADMIN
#12 1.304 14 | }
#12 1.304    | 
#12 1.304 
#12 1.304 Validation Error Count: 1
#12 1.304 [Context: getDmmf]
#12 1.304 
#12 1.304 Prisma CLI Version : 4.12.0
------
executor failed running [/bin/sh -c npx prisma generate      && npx prisma migrate dev --name init      && npx prisma db push]: exit code: 1
Unable to find image 'agentgpt:latest' locally
docker: Error response from daemon: pull access denied for agentgpt, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
`

Did I miss a step in the setup, or is there a larger issue?

**Comment by exilvm** [comment]
I believe the issue was fixed in #206.

You should pull the changes into your repository.
