### ISSUE TITLE
🐛 Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by zero942520** [reworkd/AgentGPT#212]
How to slove the problem?
Unhandled Runtime Error
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Call Stack
removeChild
node_modules\react-dom\cjs\react-dom.development.js (11099:0)
commitDeletionEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24028:0)
commitDeletionEffects
node_modules\react-dom\cjs\react-dom.development.js (23976:0)
recursivelyTraverseMutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24259:0)

**Comment by Jshen123** [comment]
Hi @zero942520  can you provide the steps for reproducing this issue? :)

**Comment by WANG-GD** [comment]
When I was running AgentGPT, this issue occurred when I clicked the "Stop agent" button.
