### ISSUE TITLE
provide more guidance on temperature

### ISSUE THREAD

**Issue by markgoho** [reworkd/AgentGPT#213]
per https://gptforwork.com/guides/openai-gpt3-temperature

> For transformation tasks (extraction, standardization, format conversion, grammar fixes) prefer a temperature of 0 or up to 0.3. For writing tasks, you should juice the temperature higher, closer to 0.5. If you want GPT to be highly creative (for marketing or advertising copy for instance), consider values between 0.7 and 1.

**Comment by Jshen123** [comment]
Hi @markgoho thank you for bringing this up. To make it more descriptive, I have updated the temperature tooltip using the official verbiage from OpenAI's documentation.

> Higher values will make the output more random, while lower values make the output more focused and deterministic
