### ISSUE TITLE
💅 Fix overflow in some screens

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#22]
The styling may cause text or buttons to appear off screen with some resolutions. We should also improve the design to take up as much space as possible in smaller screens. We should also reduce padding in buttons / input fields in smaller screens. If you work on this, please include an image of the result.

**Comment by yuvrxj-afk** [comment]
Would you please mention few to restyle?

**Comment by MathiasWP** [comment]
Some parts are scuffed on my 13 inch Macbook Pro:

### AgentGPT header is outside the top of the screen
<img width="1490" alt="Screenshot 2023-04-12 at 13 58 14" src="https://user-images.githubusercontent.com/48158184/231450118-5287e784-2414-42ca-b301-984c5286e79d.png">

### The bottom buttons are overflowing
<img width="1490" alt="Screenshot 2023-04-12 at 13 58 21" src="https://user-images.githubusercontent.com/48158184/231450140-2e7b41f9-dcf1-4440-8212-68b85a39c075.png">

**Comment by UnloadingGnat** [comment]
I can work on this feel free to assign me! thanks

**Comment by asim-shrestha** [comment]
Assigned, thanks

**Comment by ranjanmangla1** [comment]
If anyone is not working on this issue, can you assign me this issue?

**Comment by yuvrxj-afk** [comment]
@asim-shrestha i raised a PR , you should review it once.
