### ISSUE TITLE
manually sets the key in the Settings interface， can't run task

### ISSUE THREAD

**Issue by linghongli** [reworkd/AgentGPT#223]
The latest version manually sets the key in the Settings interface. When executing tasks, it always prompts "ERROR accessing OpenAI APIs. Please check your API key or try again later" to confirm that the key is correct. The previous version executed without any issues
![123](https://user-images.githubusercontent.com/2770205/232644834-3f4f4d77-4db1-4b47-8029-05e4cbe0af95.png)
![22](https://user-images.githubusercontent.com/2770205/232644898-96481126-e60a-4341-97a5-d4c244f816e4.png)

**Comment by asim-shrestha** [comment]
Can you double check your key? Seems to be working on my end. You can also check the console log for a potentially more detailed error

**Comment by linghongli** [comment]
> Can you double check your key? Seems to be working on my end. You can also check the console log for a potentially more detailed error

The value of key has been confirmed multiple times and is correct. We have deployed two versions for comparative testing, and the latest version is consistent with the previous version. The old version has no issues. When saving the settings, there is no problem and it can be saved normally. However, when executing tasks, the key error “ERROR accessing OpenAI APIs. Please check your API key or try again later” will be reported. (Old version is normal) The console did not see any error messages.
![4444](https://user-images.githubusercontent.com/2770205/232663574-1f8bd069-9fb2-433e-9768-256d64872a13.png)

**Comment by tianciBR** [comment]
I have the same problem

**Comment by Sneezry** [comment]
It's possible that the OpenAI API has been restricted in China, which could be the reason for the problem. To ensure whether you have access to the OpenAI API in your local network, you may need to confirm it.

**Comment by tianciBR** [comment]
I know there is a problem in this aspect, but I used the web page provided by the author to input my APIkey, which also cannot be used normally. Is this my personal reason

**Comment by Sneezry** [comment]
If you set up your own API, I believe that your browser initiates requests to OpenAI instead of the website's backend, as it's logical to maintain your secrets on your own machine. So, if you're unable to connect to OpenAI from your local network, this could be the reason for the problem you're facing.

**Comment by tianciBR** [comment]
Thank you for your answer. I will try again to find the answer to the question

**Comment by linghongli** [comment]
> 



> If you set up your own API, I believe that your browser initiates requests to OpenAI instead of the website's backend, as it's logical to maintain your secrets on your own machine. So, if you're unable to connect to OpenAI from your local network, this could be the reason for the problem you're facing.

Not for this reason, I have deployed two versions, old and new. The latest version has issues, while the old version is normal. It's not due to the key, nor is it due to network issues. If it's due to network issues, the old version cannot execute properly

**Comment by linghongli** [comment]
It is indeed due to the local network. After switching the network, it is normal. It's quite strange, the old version is indeed normal.

**Comment by yourepicservices** [comment]
Could you provide info on what old version and what new version you're running?

**Comment by tf-taxa** [comment]
I encountered the same issue and I'm in Singapore. Doesn't look like a network accessibility issue.

**Comment by 4a9m0011** [comment]
I encountered the same issue and I'm in tw. Unlikely to be a network accessibility issue.I can guarantee that both accounts and keys are valid.![image](https://user-images.githubusercontent.com/129057698/235337520-573d0344-5155-45d2-87f7-9ce247b750b9.png)
![image](https://user-images.githubusercontent.com/129057698/235337546-b7cb1eb7-18e5-499b-bc22-685da4ad4e49.png)

**Comment by morenokosta** [comment]
Unfortunately I too have this problem in the browser version... I inserted and changed with another key but the problem remains

**Comment by asim-shrestha** [comment]
Hey so when you use your own key, you run all of the code and API calls on the client side. If the API is not available in your region (Which seems to be the cause for these) then you will unfortunately receive this error

**Comment by jasangill1** [comment]
Hello @Sneezry @linghongli @tf-taxa @yourepicservices Please Try the new updates which may have resolved these if sill experiencing these issues feel free to reopen this or find a newer issue that has the same problems!!!!
