### ISSUE TITLE
🌎 Support for web search

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#23]
We need to integrate with langchang agents api to allow the agent to make google searches for answers. This will need a google api key that is production allowlisted

**Comment by seshubonam** [comment]
Other langchain agents and tools available in agentgpt? is it built on langchain

**Comment by rogerserper** [comment]
https://python.langchain.com/en/latest/modules/agents/tools/examples/search_tools.html might be useful! Let me know if you need any help integrating with [serper.dev](https://serper.dev)

**Comment by asim-shrestha** [comment]
Thanks @rogerserper, a bit outdated now but we've added the search tool!

Also @seshubonam yes they are! Though we have our own tool middleware for ease of integration (https://github.com/reworkd/AgentGPT/tree/main/platform/reworkd_platform/web/api/agent/tools)

Closing!

**Comment by superlbr** [comment]
search content could be messy。。font related?
![de65ffb0f990c37588c1110cae7d249](https://github.com/reworkd/AgentGPT/assets/8142164/50708202-883a-4268-a900-a71983acb1ad)
