### ISSUE TITLE
🗣 Multi-language translation based on browser language

### ISSUE THREAD

**Issue by gglzl** [reworkd/AgentGPT#253]
Edit from Asim:

Custom translations of the site / prompt. The default value of this will be the determined browser language. If there is no translation to the detected language then we will fall back to English. We should also have a dropdown or a pop-up modal which will allow the user to change only the language of the UI. 

i18next will most likely be used for internationalization.

**Comment by asim-shrestha** [comment]
@Cs4K1Sr4C going to assign you to this given you're looking into multi language translations across the app

**Comment by asim-shrestha** [comment]
Handled a bit in #326. @Cs4K1Sr4C is also working on translations on the prompt side
