### ISSUE TITLE
✨ Ability to manually input a task

### ISSUE THREAD

**Issue by ThalliumFrog** [reworkd/AgentGPT#254]
I’d like to be able to give AgentGPT a task while it’s running to make it change some things that are not optimal.

**Comment by asim-shrestha** [comment]
Hey reworded this a bit to specify just tasks. @Jshen123 will be looking into this

For more general prompts, we have #258

**Comment by asim-shrestha** [comment]
The ability to manually input a task has been added! 

![image](https://github.com/reworkd/AgentGPT/assets/50181239/c8e6e35e-2334-48f8-b4df-bd6437c52289)

@Jshen123 also has a PR to edit an existing task: https://github.com/reworkd/AgentGPT/pull/467
