### ISSUE TITLE
✨ Save API key to account

### ISSUE THREAD

**Issue by KWaltherRavn** [reworkd/AgentGPT#255]
I can use AgentGPT just fine, but have to enter me API-key from platform.openai every time. I'm unsure exactly when it resets/removes the api-key.

**Comment by asim-shrestha** [comment]
Hey we don't save any keys locally at the moment just for security. When you refresh / re-open the page you'll have to repopulate the field. 

Now that we have user auth, we can look into saving keys when you are signed in

**Comment by SunilWarrier** [comment]
This is greatly necessary as I had to regenerate several times. Currently, I possess the key in a file, it would be wise to save it along with the login credentials.

2 / 2
