### ISSUE TITLE
🗄 Make left drawer collapsible even on large screens

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#261]
![image](https://user-images.githubusercontent.com/50181239/233157234-e1e97b98-6f7b-41b9-9206-83655f1af81e.png)

In small screens, this left drawer collapses. We should also do the same thing in larger screens, allowing for more screen space to read the Agent runs. Note the ChatWindow div currently has a max height, we should look into making this a larger value as well

**Comment by 2022H1030042G** [comment]
Hi, is the issue available? I would like to work on it.

**Comment by asim-shrestha** [comment]
Yup! @2022H1030042G, gone ahead and assigned you

**Comment by 2022H1030042G** [comment]
Can you help me with this? I'm new to open source development.

**Comment by 2022H1030042G** [comment]
@rp-bot , While setting up the project, where do I have to create .env file as mentioned here:  https://github.com/reworkd/AgentGPT#:~:text=Create%20a%20.env%20file%20with%20the%20following%20content

**Comment by 2022H1030042G** [comment]
@rp-bot , Thanks for the information. Can I set it up on Windows?

**Comment by 2022H1030042G** [comment]
Okay, I created a .env file inside the Agent GPT folder and after running this command : https://github.com/reworkd/AgentGPT#:~:text=Ready,%2C%20now%20run%3A , I got this error: 
![image](https://user-images.githubusercontent.com/17452290/233639221-ebe8fb3c-d26a-44a5-87b5-a37f0efc878d.png)

**Comment by 2022H1030042G** [comment]
@rp-bot , @asim-shrestha , I am able to setup AgentGPT locally, now if can anyone help me with the changes that are required in a particular file.

**Comment by 2022H1030042G** [comment]
fix #307
