### ISSUE TITLE
🐛 Fix code formatting

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#265]
![image](https://user-images.githubusercontent.com/50181239/233164259-573795cf-8bfb-48f1-a590-61f49e7f2811.png)

We use a markdown formatter for code formatting. In cases where the provided text from GPT is 

"``` {CODE}```" instead of "python```{CODE}```" no formatting is used. We should still have a default display that shows it is code and not just a regular string.

**Comment by matthope1** [comment]
I can work on this either tonight or tomorrow morning

**Comment by matthope1** [comment]
@asim-shrestha or @reworkd-admin 
Does anyone have a text example from chatgpt where the formatting is displayed correctly?
In my testing the formatting has never worked & code is always displayed as a string.

![image](https://user-images.githubusercontent.com/17298648/233460989-0683cd06-b5e4-4eb4-8e66-49cf00c16767.png)

**Comment by awtkns** [comment]
@rp-bot woulsnyou be able to share your code for this?

**Comment by raj2033** [comment]
@rp-bot Did you initiate PR? Would love to see what you did there.

**Comment by asim-shrestha** [comment]
Has been fixed! Codeformatting now displays like so:

![image](https://github.com/reworkd/AgentGPT/assets/50181239/4f35fecc-3b73-40b7-8bf5-3cae1280e512)
