### ISSUE TITLE
© Add ability to copy formatted sections

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#266]
![image](https://user-images.githubusercontent.com/50181239/233165008-9581ac2f-21f2-4fb2-a5b4-de9a4f9f85b2.png)

ChatGPTs formatter adds a copy code button to the top right making it easy to copy the code directly from the chat message.

AgentGPT doesn't currently support that but it should be possible via the formatter we use.
![image](https://user-images.githubusercontent.com/50181239/233164917-61309641-fa61-449a-a4a8-3d334a5b1149.png)

**Comment by jasangill1** [comment]
Copy button added!!!
