### ISSUE TITLE
Do Extra steps need to be taken to enable authorization?

### ISSUE THREAD

**Issue by Krishnacore** [reworkd/AgentGPT#272]
I see that you have a user authorization option on your site. But I don't see it locally. No button to login + 404 and 500 errors in the console. Maybe this needs to be configured in some additional way?  
![Screenshot 2023-04-19 at 6 02 12 PM](https://user-images.githubusercontent.com/30728017/233210285-beb1d49f-17bf-4834-b1c8-aac3e443db05.png)
![Screenshot 2023-04-19 at 5 59 29 PM](https://user-images.githubusercontent.com/30728017/233210289-7afe2b52-2112-448d-9aee-1c1c8fd95dc0.png)

**Comment by linghongli** [comment]
Same issue

**Comment by linghongli** [comment]
> NEXT_PUBLIC_VERCEL_ENV=production
> NEXT_PUBLIC_FF_AUTH_ENABLED=true
> NEXT_PUBLIC_FF_SUB_ENABLED=true
> GOOGLE_CLIENT_ID=" "
> GOOGLE_CLIENT_SECRET=" "
> GITHUB_CLIENT_ID=" "
> GITHUB_CLIENT_SECRET=" "
> DISCORD_CLIENT_ID=" "
> DISCORD_CLIENT_SECRET=" "

Where is the description of this configuration on the git warehouse? There seems to be no place specifically mentioning these configuration items

**Comment by qcgm1978** [comment]
I think the authors wanted to implement/open it in the future

**Comment by asim-shrestha** [comment]
Hey folks, yeah we've added this in recently which does add a bit of overhead on the local dev side. We'll be updating our env example and documentation in the future to be able to make this clearer and demonstrate how to set this up locally

**Comment by asim-shrestha** [comment]
Hey folks, so now running locally there is an insecure authentication method that you're free to use.

Otherwise, we will be adding docs to connect with the other existing providers (Google / GitHub / Discord) 

This can be found here: https://github.com/reworkd/AgentGPT/issues/682

**Comment by asim-shrestha** [comment]
@Krishnacore  @linghongli
