### ISSUE TITLE
Copying text from PDF does not match text on screen

### ISSUE THREAD

**Issue by hahayusuf** [reworkd/AgentGPT#275]
For example, the highlighted text from the following PDF

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/101795434/233234072-c4987adc-1021-485b-992b-d1e82ae54e4f.png">

When pasted, provides the following text:

`
Task 1: After analyzing existing designs and researching innovative solutions, I have identi.ed several ways to create something newO qne approach is to combine multiple existing ideas to create a uniUue hybrid designO Another approach is to use new materials or technologies to create a more e4cient, sustainable, or aesthetically pleasing productO Additionally, exploring new user needs and behaviors can inspire creative solutionsO Eltimately, the key to creating something new is to approach the problem with an open mind, a willingness to take risks, and a commitment to continuous learning and improvementO
`

**Comment by asim-shrestha** [comment]
Hey we've since updated the output formatting. Is this still something you're experiencing?

**Comment by guifeliper** [comment]
> Hey we've since updated the output formatting. Is this still something you're experiencing?

Yes, it is still a little bit year for me. 

This is my result from copying anything from the PDF: 
,	

dd	

 m	

	



**Comment by awtkns** [comment]
fixed in #465
