### ISSUE TITLE
Will it support manual configuration of subtask functions？

### ISSUE THREAD

**Issue by linghongli** [reworkd/AgentGPT#276]
Will the official add the function of manually setting sub tasks? At present, after the framework sets goals, the setting of subtasks is completely automated and divergent. This is not very friendly for achieving some specific goals, and the completion of some goals may require manual splitting into clear subtasks. I think similar frameworks have this feature support, but I'm not sure if there is an official plan to support this feature?

**Comment by linghongli** [comment]
![4442](https://user-images.githubusercontent.com/2770205/233247740-e3e3495a-5ccd-433c-b71d-62a6471b61f6.png)

Reference examples

**Comment by asim-shrestha** [comment]
Hey, thank you for the feedback!

We now have the ability to input custom tasks within the task window: 

![image](https://github.com/reworkd/AgentGPT/assets/50181239/47968d3d-e598-4df3-8852-e65bbeab1eaa)
