### ISSUE TITLE
how is it browsing the internet  ?

### ISSUE THREAD

**Issue by arian0zen** [reworkd/AgentGPT#279]
I does web scraping so smoothly, I was wondering how does this execute that ?
can anyone help ? and can anyone let me know where the code for that is written ?

**Comment by tommymaher15** [comment]
I'm not entirely sure, but I believe that it is leveraging langchain. Don't hold me on that. 

That seems to be the way most agents are accessing the internet currently but again, I am not entirely sure documentation on this side of things is very sparse.

**Comment by jasangill1** [comment]
Hello @arian0zen @tommymaher15 please reference this for your answers : https://github.com/reworkd/AgentGPT/issues/299
