### ISSUE TITLE
🐛 Markdown formatting for lists is incorrect

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#295]
![image](https://user-images.githubusercontent.com/50181239/233553326-0c76de60-5bb2-43db-b85b-0bcfdd27d6fd.png)

The list items are properly parsed as HTML via a library but the rendering does not display bullets

**Comment by souravghosh01** [comment]
@asim-shrestha I want to work on this issue, Please mention the Steps to reproduce.

**Comment by asim-shrestha** [comment]
Sorry @souravghosh01, we've actually completed this!
