### ISSUE TITLE
problem with encoding when exporting pdf

### ISSUE THREAD

**Issue by osirisnew** [reworkd/AgentGPT#296]
when exporting instead of text, there are some incomprehensible characters, there may be a problem with fonts or encoding

**Comment by exilvm** [comment]
Can you show an example/screenshot?

**Comment by osirisnew** [comment]
[my-document-5.pdf](https://github.com/reworkd/AgentGPT/files/11295022/my-document-5.pdf)
<img width="775" alt="Снимок экрана 2023-04-21 в 13 45 23" src="https://user-images.githubusercontent.com/5052735/233617305-b866935b-2804-4a51-b4b9-cb82a358992b.png">

**Comment by osirisnew** [comment]
part of the text in Russian or Ukrainian

**Comment by belikers** [comment]
You can try modifying the font library in src/components/pdf/MyDocument.tsx.You need to find a font library that supports the language you need.

**Comment by asim-shrestha** [comment]
Copy of #275. Are you still facing this issue after the above change?

**Comment by awtkns** [comment]
fixed in #465
