### ISSUE TITLE
How do I sign in?

### ISSUE THREAD

**Issue by joshholly** [reworkd/AgentGPT#318]
It says sign in to be able to control agents. I configured the NEXT auth. But i don't see any sign in buttons.

**Comment by jskalant** [comment]
Hey @joshholly try to set NEXT_PUBLIC_FF_AUTH_ENABLED=true on your .env

**Comment by darth-pika-hu** [comment]
@joshholly @jskalant Change NODE_ENV to production.

**Comment by asim-shrestha** [comment]
Hey we have since stopped forcing sign in for local development

This is done through an env value that is false by default:

```
NEXT_PUBLIC_FORCE_AUTH=false
```

Closing

**Comment by asim-shrestha** [comment]
The sign in buttons should be within the side drawer

![image](https://github.com/reworkd/AgentGPT/assets/50181239/9df23f05-5e75-4ea9-882c-1b386606d9f4)
