### ISSUE TITLE
Is it broken?

### ISSUE THREAD

**Issue by DavidGP** [reworkd/AgentGPT#325]
I always only get "ERROR using your OpenAI API key. You've exceeded your current quota, please check your plan and billing details", no matter if I'm logged out, or logged in, having provided my v.3.5 API key from platform.openai.com/account/api-keys.

**Comment by asim-shrestha** [comment]
Go to your usage page: https://platform.openai.com/account/usage

Probably you don't have any free credits and you need to add your payment information

**Comment by DavidGP** [comment]
It says there:
> Billing overview
> You are currently on the free trial. Head over to your Usage page to view how many free trial credits are remaining on your account.

I don't get it. I believe that I'm not on a "free trial" since I'm subscribed to ChatGPT v.4?

Or do I have to subscribe to something additional in order to get API access?

**Comment by asim-shrestha** [comment]
Hey yeah this is separate from ChatGPT plus. You will need to add your payment information into OpenAI APIs: https://platform.openai.com/account/billing/overview

It will look like so:
![image](https://user-images.githubusercontent.com/50181239/233870124-5bcb866d-d788-4e4a-ac8f-02b20918094f.png)

Using gpt-3.5-turbo, it will only cost you a couple cents to run

**Comment by DavidGP** [comment]
Thanks!
