### ISSUE TITLE
🐛 Filter more bad tasks

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#328]
As before with #75 we should filter non tasks like the below:

![image](https://user-images.githubusercontent.com/50181239/233871574-963b61d9-35f3-4a01-b304-23e331dcbb75.png)

Use the existing filter code.

We should also filter for
- None
- Empty string / White space string
- Nothing
- Ask ChatGPT what else it could produce and filter those as well

**Comment by Aditya-13** [comment]
Hey, @asim-shrestha, please assign this task to me. 

Also i think empty string is fixed now, now the button is disabled even if you entered white spaces, i'll take care for rest.

**Comment by awtkns** [comment]
@Aditya-13 you can happily take it 😀

**Comment by Aditya-13** [comment]
Hey, @asim-shrestha , i have a doubt here,

Are you talking about the deploy agent button which should remain disabled when user passes something like "none" or "nothing". 
 
 LIKE THIS :--
 
![Screenshot from 2023-04-25 01-01-45](https://user-images.githubusercontent.com/91950158/234097571-24448b1f-c8c2-414d-bbf3-61a810dd90a8.png)

 
 or are you talking about making changes in this function here :--
 
 
![Screenshot from 2023-04-25 01-09-45](https://user-images.githubusercontent.com/91950158/234098834-1ed6ffa0-0f80-49b0-91b8-977f0bbf890c.png)

**Comment by Aditya-13** [comment]
@asim-shrestha , @awtkns , any Update?

**Comment by asim-shrestha** [comment]
Hey sorry, we've gone ahead and updated our filtering in the background. Appreciate the help though @Aditya-13 !
