### ISSUE TITLE
🤖 Add option to use GPT-4

### ISSUE THREAD

**Issue by avelican** [reworkd/AgentGPT#33]
Many of your users have access to GPT-4 already. I checked the settings but there is no option to use it. I checked the code, and the model name is baked-in as gpt-3.5-turbo. It would be very nice to have a GPT-4 option considering the difference in quality.
(Might be worth adding a notice that using GPT-4 will be slower and more expensive.)

**Comment by OVAWARE** [comment]
I would agree. Allow users to choose between GPT-3.5, 3 and 4 when they have there custom token.

**Comment by gauravsaini** [comment]
https://github.com/reworkd/AgentGPT/pull/39

**Comment by asim-shrestha** [comment]
Thanks @gauravsaini that will help on the dev side, for production usage @Jshen123 is working on something

**Comment by Jshen123** [comment]
PR for #88

**Comment by yourepicservices** [comment]
Model input has been added in settings
