### ISSUE TITLE
🐛 When the interface is in Chinese, there is an issue with the display position of the image

### ISSUE THREAD

**Issue by linghongli** [reworkd/AgentGPT#331]
When the interface is in Chinese, there is an issue with the display position of the image

![333](https://user-images.githubusercontent.com/2770205/233894047-048c9e05-d4a1-4e77-a840-a495609dfb9f.png)

Steps to reproduce:
- Go to settings
- Change language to Chinese
- Badge in landing page will now cover the title

**Comment by awtkns** [comment]
@Nodewarrior yes go ahead :)

**Comment by asim-shrestha** [comment]
![image](https://user-images.githubusercontent.com/50181239/235341061-01117545-de15-40ec-a63b-650c0f3f8b25.png)

Fixed!

https://github.com/reworkd/AgentGPT/commit/a06095d9d2b9664b4cd4493f31285625825338f8
