### ISSUE TITLE
😵 Update settings logic

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#344]
So advanced settings features are only available if a user provides their own API key. We also perform some client side validation to ensure the API key provided by the client is correct.

The issue is, is this validation always runs regardless of whether or not the user changes any settings. This means the user can
- Open settings
- Do nothing
- Click save
- Get "Key is invalid, please ensure that you have set up billing in your OpenAI account!" when they didn't change anything

This is confusing for users. We should place the model selection within advanced settings as well and just gray it out if no api key is provided. We shouldn't run this validation if the user doesn't touch the API key

**Comment by l2hyunwoo** [comment]
Can I take this issue?

**Comment by awtkns** [comment]
@l2hyunwoo its yours 😀

**Comment by asim-shrestha** [comment]
Assigned!

**Comment by jasangill1** [comment]
Hello @abhithory this issue as been resolved as we added a new validation system and new settings component!!
