### ISSUE TITLE
Implement pause calculation functionality

### ISSUE THREAD

**Issue by vvatikiotis** [reworkd/AgentGPT#350]

**Comment by Jshen123** [comment]
Hi @vvatikiotis, thanks for bringing this up :) We are planning to address this in an upcoming PR.

It will be part of a several PRs to implement #254

**Comment by yourepicservices** [comment]
Can you please provide more information?

**Comment by asim-shrestha** [comment]
Hey, so we have a new default mode called "Pause mode" that will automatically wait before continuing with tasks. 

We will also be implementing a direct pause feature where you'll be able to pause at any point of execution. Closing
