### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by drakopyan** [reworkd/AgentGPT#353]
Hi Agent GPT team. I am new at this so If my question seems dumb I am sorry. I use the beta version to generate a summary of news articles relating to a very specific topic from around the world. It did the job fine and I was impressed. BUT, none of the relevant links to the news articles worked. They were all dead links. Is this something I am doing wrong? or is this a known issue. Thank you in advance.

**Comment by asim-shrestha** [comment]
Hey! It must have been hallucinating these links at that time. We've since done a google search integration that provided legitimate links. We've momentarily turned off the display for these links, but we'll be adding them back in the future. 

Closing this ticket.
