### ISSUE TITLE
ETA of Roadmap Milestones

### ISSUE THREAD

**Issue by danielHype** [reworkd/AgentGPT#355]
With Langchain announcing their new AutoGPT JS implementation, can you please give an ETA on different roadmap milestones communicated from the project? 

Mostly of interest is: 
Web browsing capabilities via LangChain 🌐
Writing capabilities via a document API 📄

The tweet mentioning the new Langchain JS implementation: https://twitter.com/nfcampos/status/1649497491514052610

Thanks!

**Comment by asim-shrestha** [comment]
Hey web browsing should come within the week. Ideally we could just integrate LangChain directly but the issues are that the `edge` runtime used by Vercel doesn't work with some of the LangChain dependencies. We also need to consider userbase size and ease of local development when thinking about tools like a Vector DB.

Better writing capabilities are also on the horizon. We're thinking something like the google docs API to start but would love suggestions here

**Comment by linghongli** [comment]
> Hey web browsing should come within the week. Ideally we could just integrate LangChain directly but the issues are that the `edge` runtime used by Vercel doesn't work with some of the LangChain dependencies. We also need to consider userbase size and ease of local development when thinking about tools like a Vector DB.
> 
> Better writing capabilities are also on the horizon. We're thinking something like the google docs API to start but would love suggestions here

fantastic，Exciting news

**Comment by thepeacedude** [comment]
Awesome news!  Thank you!

**Comment by yourepicservices** [comment]
We should consider setting up the project workspace here for roadmap transparency.

**Comment by linghongli** [comment]
> We should consider setting up the project workspace here for roadmap transparency.

excellent

**Comment by asim-shrestha** [comment]
Hey, created some documentation to outline the roadmap: https://reworkd.github.io/AgentGPT-Documentation/docs/roadmap

We'll also open up the GitHub project board
