### ISSUE TITLE
Export PDF font overflow problem

### ISSUE THREAD

**Issue by AtaraxiaRun** [reworkd/AgentGPT#358]
![image](https://user-images.githubusercontent.com/31299873/234500450-73f1c290-a855-4ce3-af51-69b797a99d6a.png)

**Comment by AtaraxiaRun** [comment]
提示：写一篇2000字的门锁市场报告,将报告转换成中文进行输出
Tip: WRITE a 2000 word report on the door lock market, and convert the report into Chinese for output

**Comment by pengfeiu** [comment]
> 提示：写一篇2000字的门锁市场报告,将报告转换成中文进行输出 Tip: WRITE a 2000 word report on the door lock market, and convert the report into Chinese for output

怎么支持中文

**Comment by awtkns** [comment]
fixed in #465
