### ISSUE TITLE
🐛 Z-Index Issue in Settings dropdown

### ISSUE THREAD

**Issue by awtkns** [reworkd/AgentGPT#361]
When the settings drop down is open, it overlaps with the model dropdown.

<img width="848" alt="Screen Shot 2023-04-26 at 11 58 56 AM" src="https://user-images.githubusercontent.com/32209255/234555767-709bc3f4-bdf9-470f-8a0f-931c21fda2c2.png">

This issue is open for anyone that wants it :)

**Comment by giri-madhan** [comment]
Hi @awtkns , I have created an PR with a fix for this issue here - https://github.com/reworkd/AgentGPT/pull/369

Thanks!
