### ISSUE TITLE
Error when exporting PDF

### ISSUE THREAD

**Issue by belikers** [reworkd/AgentGPT#378]
![Snipaste_2023-04-27_16-43-12](https://user-images.githubusercontent.com/109145789/234816302-1d8c42a0-8ecb-4f14-ac96-3cd1937a00fa.jpg)
![Snipaste_2023-04-27_16-43-25](https://user-images.githubusercontent.com/109145789/234816324-ab4497c0-77b2-46ce-a63a-394c41e57dc0.jpg)
Duplicate content appears after exporting PDF and does not display completely.

**Comment by belikers** [comment]
![Snipaste_2023-04-27_17-17-32](https://user-images.githubusercontent.com/109145789/234817965-7826a801-98c7-4b2c-b367-1d9104d33d5f.jpg)
The results are also not displayed.

**Comment by jakubmatej** [comment]
I have the same issue.
Plus the text inside PDF can't by copied. E.g. if you copy/paste the Goal sentence you receive only "Goal: {unknow symbol}"

**Comment by darth-pika-hu** [comment]
Same here; even using the official site has the same issue.

**Comment by awtkns** [comment]
fixed in #465
