### ISSUE TITLE
I can't see the code. Can it produce code?

### ISSUE THREAD

**Issue by 14790897** [reworkd/AgentGPT#386]

**Comment by Boostrix** [comment]
this sort of stuff is transparently handled behind the scenes, the auto-gpt backend is handling this, so any files that will be created will show up in the corresponding workspace of the docker container.

Like you said, it's not very well integrated currently, i.e. while it is possible to "export" the conversation/chat, there is no good integration to just export some of the results (aka files/directories) that the agent creates.

But things are working behind the scenes, to see for yourself, just execute the following and enter the "hello" directory in your auto-gpt workspace afterwards:

"write a helloWorld.c program to a sub-directory named "hello" including a corresponding CMakeLists.txt file"

**Comment by asim-shrestha** [comment]
Yup! Its able to output formatted code in the text windows, heres an example (Scroll down a bit) https://agentgpt.reworkd.ai/agent?id=clh3tc8sh0i81l708mzv4sti8

It may say that it added code to a file or something along those lines. This is not actually supported at the moment. Our Roadmap for more details: https://docs.reworkd.ai/roadmap
