### ISSUE TITLE
I was hoping he would be able to network the search time, but the search came up wrong

### ISSUE THREAD

**Issue by lianli2352** [reworkd/AgentGPT#389]
![image](https://user-images.githubusercontent.com/66762104/235082787-a46ad7b5-408d-48b3-a8b6-a2c50f29908a.png)

**Comment by asim-shrestha** [comment]
Hey at the time of this issue, it was not connected to google search. We have this functionality available in limited capacity. Please view the roadmap for more info: https://reworkd.github.io/AgentGPT-Documentation/docs/roadmap
