### ISSUE TITLE
Change another language but it still english

### ISSUE THREAD

**Issue by wqjuser** [reworkd/AgentGPT#402]
when i change to another language ui still shwo me english
<img width="1130" alt="Snipaste_2023-04-29_14-57-55" src="https://user-images.githubusercontent.com/19888942/235288857-4e21a98d-8676-4f2c-a11f-fe4cd69398d4.png">
<img width="1013" alt="Snipaste_2023-04-29_14-58-39" src="https://user-images.githubusercontent.com/19888942/235288870-aa93bed9-7feb-4f28-aaf0-774cf1b109f9.png">

**Comment by wqjuser** [comment]
your pr have not merged

**Comment by bobolau** [comment]
> #399
The suggestion is to prioritize the language of the task entered by the current user as the agentLanguage.

**Comment by asim-shrestha** [comment]
Added in now, thanks @Cs4K1Sr4C! Closing
