### ISSUE TITLE
Wasn't this tool the one where we could define our sub-tasks?

### ISSUE THREAD

**Issue by MR-T77** [reworkd/AgentGPT#404]
Sorry in advance, but I'm almost sure I've had access to define our sub-tasks in AgentGPT. Did you change the interface?

**Comment by onekum** [comment]
You might be thinking of Auto-GPT.

**Comment by MR-T77** [comment]
I haven't yet tried Auto-GPT. I tried Nando.Ai in tandem with another tool, which I was almost certain it was Auto-GPT...Anyway, thanks for your answer.
