### ISSUE TITLE
Weblink for code note avialable

### ISSUE THREAD

**Issue by petelindsey** [reworkd/AgentGPT#408]
the agent I started was supposed to generate code, but I cannot find the code at the link it provided
which was, https://github.com/agentgpt/Python-AI-with-self-modification... perhaps this is a privacy thing?

Can you check if the code was actually made?

**Comment by asim-shrestha** [comment]
Unfortunately its not able to output real links at the moment. FAQ here: https://reworkd.github.io/AgentGPT-Documentation/docs/faq
