### ISSUE TITLE
Content Overflowing on homepage and a part of logo is not visible.

### ISSUE THREAD

**Issue by prathamjagga** [reworkd/AgentGPT#41]
![image](https://user-images.githubusercontent.com/30550632/231385938-f478cb9c-4b51-4a62-b23d-20d3d6d1f6a7.png)
You can clearly see the home page is overflowing in x and y directions and a part of logo is not visible.
Screen Size: 15.6 inches.

**Comment by w3tsa** [comment]
I tested It and looks like it might only be happening on 13-inch laptops.

**Comment by Elgius** [comment]
putting the them in a container class from tailwind css might solve it.  if the admins dont mind, i could take up this issue and test a couple of solutions. 👀

**Comment by asim-shrestha** [comment]
Partial duplicate of #22, I think someone is handling it there already. Lets move discussion there
