### ISSUE TITLE
🐛 Cannot find module 'react-icons/Bi' or its corresponding type declarations.

### ISSUE THREAD

**Issue by changkuanlai** [reworkd/AgentGPT#410]
#0 26.29 Failed to compile.
#0 26.29 
#0 26.29 ./src/components/ChatWindow.tsx:32:26
#0 26.29 Type error: Cannot find module 'react-icons/Bi' or its corresponding type declarations.
#0 26.29 
#0 26.29   30 | import type { Translation } from "../utils/types";
#0 26.29   31 | import { AnimatePresence } from "framer-motion";
#0 26.29 > 32 | import { BiExport } from "react-icons/Bi";
#0 26.29      |                          ^
#0 26.29   33 | 
#0 26.29   34 | interface ChatWindowProps extends HeaderProps {
#0 26.29   35 |   children?: ReactNode;

**Comment by asim-shrestha** [comment]
Hey, our production deployment was facing the same issue. We've updated to use CgExport instead which seems to work. Are you still facing this issue?

**Comment by awtkns** [comment]
Related to #409
