### ISSUE TITLE
Error when deploying agent

### ISSUE THREAD

**Issue by Deca** [reworkd/AgentGPT#42]
Getting this error when "deploy agent" button is clicked (sensible data replaced with ... )
The prompt was a simple "plan a week of ketogenic diet"
On the frontend side I get "ERROR retrieving initial tasks array. Make sure your API key is not the free tier, make your goal more clear, or revise your goal such that it is within our model's policies to run. Shutting Down."
Is there a free tier openai API key? I'm not aware of, anyway mine  under a billing usage 

`error - AxiosError: Request failed with status code 401
    at createError (file:///.../AgentGPT/node_modules/langchain/dist/util/axios-fetch-adapter.js:307:16)
    at settle (file:///.../AgentGPT/node_modules/langchain/dist/util/axios-fetch-adapter.js:26:16)
    at file:///.../AgentGPT/node_modules/langchain/dist/util/axios-fetch-adapter.js:176:19
    at new Promise (<anonymous>)
    at fetchAdapter (file:///.../AgentGPT/node_modules/langchain/dist/util/axios-fetch-adapter.js:168:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [AsyncFunction: fetchAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'OpenAI/NodeJS/3.2.1',
      Authorization: 'Bearer ...'
    },
    method: 'post',
    data: '{"model":"gpt-3.5-turbo","temperature":0.9,"top_p":1,"frequency_penalty":0,"presence_penalty":0,"n":1,"max_tokens":300,"stream":false,"messages":[{"role":"user","content":"You are an autonomous task creation AI called AgentGPT. You have the following objective `plan a week of ketogenic diet`. Create a list of zero to three tasks to be completed by your AI system such that your goal is more closely reached or completely reached. Return the response as an array of strings that can be used in JSON.parse()"}]}',
    url: 'https://api.openai.com/v1/chat/completions'
  },
  request: Request {
    [Symbol(realm)]: { settingsObject: [Object] },
    [Symbol(state)]: {
      method: 'POST',
      localURLsOnly: false,
      unsafeRequest: false,
      body: [Object],
      client: [Object],
      reservedClient: null,
      replacesClientId: '',
      window: 'client',
      keepalive: false,
      serviceWorkers: 'all',
      initiator: '',
      destination: '',
      priority: null,
      origin: 'client',
      policyContainer: 'client',
      referrer: 'client',
      referrerPolicy: '',
      mode: 'cors',
      useCORSPreflightFlag: false,
      credentials: 'same-origin',
      useCredentials: false,
      cache: 'default',
      redirect: 'follow',
      integrity: '',
      cryptoGraphicsNonceMetadata: '',
      parserMetadata: '',
      reloadNavigation: false,
      historyNavigation: false,
      userActivation: false,
      taintedOrigin: false,
      redirectCount: 0,
      responseTainting: 'basic',
      preventNoCacheCacheControlHeaderModification: false,
      done: false,
      timingAllowFailed: false,
      headersList: [HeadersList],
      urlList: [Array],
      url: [URL]
    },
    [Symbol(signal)]: AbortSignal { aborted: false },
    [Symbol(headers)]: HeadersList {
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  },
  response: {
    ok: false,
    status: 401,
    statusText: 'Unauthorized',
    headers: HeadersList {
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    config: {
      transitional: [Object],
      adapter: [AsyncFunction: fetchAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'post',
      data: '{"model":"gpt-3.5-turbo","temperature":0.9,"top_p":1,"frequency_penalty":0,"presence_penalty":0,"n":1,"max_tokens":300,"stream":false,"messages":[{"role":"user","content":"You are an autonomous task creation AI called AgentGPT. You have the following objective `plan a week of ketogenic diet`. Create a list of zero to three tasks to be completed by your AI system such that your goal is more closely reached or completely reached. Return the response as an array of strings that can be used in JSON.parse()"}]}',
      url: 'https://api.openai.com/v1/chat/completions'
    },
    request: Request {
      [Symbol(realm)]: [Object],
      [Symbol(state)]: [Object],
      [Symbol(signal)]: [AbortSignal],
      [Symbol(headers)]: [HeadersList]
    },
    data: { error: [Object] }
  },
  page: '/api/chain'
}`

**Comment by prathamjagga** [comment]
you can try to make your goal more clear or try with a paraphrased version of your goal.

**Comment by Deca** [comment]
I tried with different kind of prompts but no matter what I put in the goal field I receive the same error

**Comment by matthope1** [comment]
@Deca, are you still getting the error? I can't reproduce with that prompt
![keto](https://user-images.githubusercontent.com/17298648/231556352-af579334-4745-40e7-bfdd-9bcb2daf4354.png)

**Comment by Deca** [comment]
Ahh I got it! 
Since I'm from Italy I can't reach openai endpoint, with a vpn it works fine. 
Sorry for the mistake I should have known that from the start

**Comment by njsmithpro** [comment]
Mine's not working either. Changed IP through a VPN. Same error
