### ISSUE TITLE
ERROR: Failed to search as no SERP_API_KEY is provided in ENV.

### ISSUE THREAD

**Issue by darth-pika-hu** [reworkd/AgentGPT#422]
I noticed this error when enabling web search. 
ERROR: Failed to search as no SERP_API_KEY is provided in ENV.
What is SERP_API_KEY?

**Comment by zahir2000** [comment]
It is used for scraping search results. You can sign up here: https://serpapi.com/users/sign_up and it should generate a key for you.

Paste it in this file:
https://github.com/reworkd/AgentGPT/blob/8810ae2ee4db52fef84d31789c21406f0ce53bd9/src/services/custom-tools/serper.ts#L26

**Comment by darth-pika-hu** [comment]
Any benefit over Google API and CSE?

**Comment by asim-shrestha** [comment]
@darth-pika-hu Mostly just price and scalability. When we turned it on we hit 50k + requests in under 8 hours. I think the google API only allows for 10k searches a day

**Comment by asim-shrestha** [comment]
Thanks @zahir2000!

**Comment by darth-pika-hu** [comment]
@asim-shrestha How about giving users options can use their Google API?

**Comment by bigsk1** [comment]
> @darth-pika-hu Mostly just price and scalability. When we turned it on we hit 50k + requests in under 8 hours. I think the google API only allows for 10k searches a day

how much is 50k request in $$ amount?

**Comment by darth-pika-hu** [comment]
@bigsk1 i don't care. Company pays it.

**Comment by darth-pika-hu** [comment]
Just let user use their own API

**Comment by yf007** [comment]
> It is used for scraping search results. You can sign up here: https://serpapi.com/users/sign_up and it should generate a key for you.
> 
> Paste it in this file:
> 
> https://github.com/reworkd/AgentGPT/blob/8810ae2ee4db52fef84d31789c21406f0ce53bd9/src/services/custom-tools/serper.ts#L26

Where do I find this file?
After installing in Docker?

**Comment by asim-shrestha** [comment]
Hey folks, so if you follow our new `./setup.sh` script you can provide your own serper API key. To use google, we'd need to have another integration. Feel free to make a ticket if this is of interest to you :) In the meantime, I'll be closing this one
