### ISSUE TITLE
.env not found

### ISSUE THREAD

**Issue by mikmoth** [reworkd/AgentGPT#431]
After running the setup and then running docker, docker says: .env not found

**Comment by bigsk1** [comment]
did you change the .env.template file to .env?

**Comment by joisonwk** [comment]
same problem when running  setup.sh --docker

**Comment by alexarthurs** [comment]
Found a workaround. Install dos2unix and run:

dos2unix entrypoint.sh

then ./setup.sh --docker again.

**Comment by lauralex** [comment]
I will make a pull request, there are errors in the Dockerfile and in the entrypoint.sh file. You should make good tests for Windows, though :(

**Comment by lauralex** [comment]
This is related to #511

**Comment by asim-shrestha** [comment]
Given the other issues are closed and this had to do with windows line endings (And I'm no longer on windows) - closing

**Comment by asim-shrestha** [comment]
Thanks @lauralex and @alexarthurs !

Hope its good now @mikmoth @bigsk1 @joisonwk !
