### ISSUE TITLE
System prompts when logging in “Try signing in with a different account.”

### ISSUE THREAD

**Issue by h00cker** [reworkd/AgentGPT#440]
What is the reason for this, thank you!

**Comment by asim-shrestha** [comment]
Hey! Would love some more background here. 

- Is this when running your own version of the tool or running the production website? 
- What Sign in provider are you using? 
- Did signing in ever work for you?

**Comment by h00cker** [comment]
Thank you for your response.
	Here are my answers to your questions:
The problem occurred when I was runing the website.
I tried signing in with Google and signing in with GitHub.
I have never successfully logged in.
	Here is my process:
	Following the instructions, I ran the following command on a remote VPS (Ubuntu 22.04 x86_64) to complete the installation:
	./setup.sh --docker
	After the installation was complete, I was able to access the agentGPT web successfully by entering the address http://My VPS IP:3000 in the Edge browser on my local computer. However, when I clicked on “sign in with Google” or “sign in with GitHub”, the link in the browser was redirected to http://localhost:3000, causing the browser to fail.
	So, I modified NEXTAUTH_URL=http://localhost:3000 in setup.sh to NEXTAUTH_URL=http://My VPS IP:3000.
	then, when I try to log in, the interface displays "try signing in with a different account" in red letters.




发自我的iPhone


------------------ Original ------------------
From: Asim Shrestha ***@***.***&gt;
Date: Thu,May 4,2023 0:42 PM
To: reworkd/AgentGPT ***@***.***&gt;
Cc: Ling Jun ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [reworkd/AgentGPT] System prompts when logging in “Try signing in with a different account.” (Issue #440)





 
Hey! Would love some more background here.
  
Is this when running your own version of the tool or running the production website?
 
What Sign in provider are you using?
 
Did signing in ever work for you?

**Comment by verysun** [comment]
This is also the problem I encountered.

**Comment by linghongli** [comment]
This is also the problem I encountered.

**Comment by kendean** [comment]
I also encountered the same problem, please answer

**Comment by verysun** [comment]
Hey guys, I just comment some codes, and it works temporarily(skip login on)
[The code is here](https://github.com/reworkd/AgentGPT/blob/56777bbc034b00e84028fa13008b40740c11b173/src/pages/index.tsx#L121)
![image](https://user-images.githubusercontent.com/30220649/236404380-3144d718-9043-4ab2-8082-ebd13078142f.png)

**Comment by lnw2019** [comment]
I also encountered the same problem, please answer
