### ISSUE TITLE
disable login

### ISSUE THREAD

**Issue by Sblop** [reworkd/AgentGPT#441]
Hi,

Thanks for a great project.
I believe a lot of self-hosters might be running this project locally protected behind a reverse proxy. I myself are running this locally behind authelia password protection. - I would love the option to set an env var to DISABLE_LOGIN: true

**Comment by asim-shrestha** [comment]
Thank you for the feedback! 

So originally this check was required if running in production with the assumption that self hosters were just running locally. Just added your suggestion in this commit: https://github.com/reworkd/AgentGPT/commit/8904fc6803b3b6de021802ff31af5a03970af18b

By default, auth will not be force on the frontend. You can provide the env value of `NEXT_PUBLIC_FORCE_AUTH=true` to force this

In the future we'll also make some docs for users to set up their own Auth
