### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Unicode')

### ISSUE THREAD

**Issue by eeezae** [reworkd/AgentGPT#450]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/34007837/236365686-e28f9ef7-fc93-4c10-abc7-a28717346cce.png">

**Comment by gsherofly007** [comment]
me too

**Comment by gsherofly007** [comment]
I wait for the developer to solve the problem

**Comment by awtkns** [comment]
cc @Cs4K1Sr4C this looks related to the pdf changes you made

**Comment by awtkns** [comment]
Awesome @Cs4K1Sr4C! I've assigned it to you for now, let me know if you need any help. 😀

**Comment by awtkns** [comment]
fixed in #465

**Comment by asim-shrestha** [comment]
Closing as we haven't heard of any other issues

**Comment by gsherofly007** [comment]
您好，邮件收到
