### ISSUE TITLE
Sign in not working!

### ISSUE THREAD

**Issue by MulletDad1** [reworkd/AgentGPT#480]
So i got Agentgpt up and running in docker container but it wants me to sign in with google or github but when i click on it, i just get an error and refused to connect. does anyone know how to fix this?

**Comment by Tembeyo** [comment]
just happened to me
![image](https://user-images.githubusercontent.com/97098069/236937640-05021e5d-bb2b-4cf6-8be7-b768da43af9a.png)

**Comment by xiguadaddy** [comment]
the same with you,but it's ok to sign in in https://agentgpt.reworkd.ai/,not local.

**Comment by parthpandya1729** [comment]
I am facing the same problem.

**Comment by dst1213** [comment]
me too

**Comment by asim-shrestha** [comment]
Hey thanks for the report @BDAthans

For some clarity, local installations running in development mode will use an insecure local authentication mechanism to avoid requiring configuration for these auth providers.

For the production issue you've mentioned, me and @awtkns will have to take a deeper look

**Comment by awtkns** [comment]
Hi @BDAthans would you be able to provide your Google Oauth client configuration? The callback url in the cloud console should be `http://localhost:3000/api/auth/signin/google`

**Comment by BDAthans** [comment]
> Hi @BDAthans would you be able to provide your Google Oauth client configuration? The callback url in the cloud console should be `http://localhost:3000/api/auth/signin/google`

I'm sorry but I am not comfortable providing our specific Google Oauth information as it can potentially pose security risks if not handled properly. especially with this being a public domain. Can you explain what exactly you are looking for? When using the AgentGPT hosted on your own site, we don't have this issue or need our specific Oauth to make it work.

**Comment by BDAthans** [comment]
Also noticed another issue regarding the authentication. When the app launches it will assign to port 3001 if port 3000 is already bound at the time of launch, but when you go to 'Sign In' and authenticate, it redirects back to port 3000 instead of continuing to use port 3001.

**Comment by awtkns** [comment]
> Hi @awtkns, I'm sorry but I am not comfortable providing our specific Google Oauth information as it can potentially pose security risks if not handled properly, especially with this being a public domain.
> 
> Can you explain why what exactly you are looking for and why? When using the AgentGPT hosted on your own site, we don't have this issue or need our specific Oauth to make it work.

@BDAthans you're google cloud console configuration should look like the below assuming you are running it on port 3000. Nothing sensitive in there, just never share your secret key. 

<img width="588" alt="Screenshot 2023-05-12 at 9 27 41 PM" src="https://github.com/reworkd/AgentGPT/assets/32209255/0da59cb3-4c2b-4c1d-8462-9416badd7a03">

> Also noticed another issue regarding the authentication. When the application launches on the server it will bind to port 3001 if port 3000 is already bound at the time of launch, but when you go to 'Sign In' and authenticate, it redirects back to port 3000 instead of continuing to use port 3001.

This is expected behaviour. Typically with Oauth integrations wildcard's are not allowed and they require a hardcoded redirect url.

**Comment by jaredlutz** [comment]
I solved this by changing the editing a column in the table. The error was that the access token was too long. Fix: add @db.Text as shown below. Make sure you push the update to Planetscale :)

model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String?
  access_token      String? @db.Text
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String?
  session_state     String?
  user              User    @relation(fields: [userId], references: [id], onDelete: Cascade)

**Comment by asim-shrestha** [comment]
Glad you were able to fix it @jaredlutz :) Care to upload a PR with the fix?

**Comment by jasangill1** [comment]
Closing as the solution was found !!! If you are still facing these issues feel free to message in the issue linked here; https://github.com/reworkd/AgentGPT/issues/886
