### ISSUE TITLE
How to replace chatgpt api with personal gpt api

### ISSUE THREAD

**Issue by Song367** [reworkd/AgentGPT#487]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/reworkd/AgentGPT/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/reworkd/AgentGPT/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

How to replace chatgpt api with personal gpt api

### ✔️ Solution

How to replace chatgpt api with personal gpt api

### ❓ Alternatives

auto-gpt

### 📝 Additional Context

How to replace chatgpt api with personal gpt api

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by yhyu13** [comment]
@Song367 There is a on going PR : https://github.com/reworkd/AgentGPT/pull/84

**Comment by asim-shrestha** [comment]
Closing as the PR exists

**Comment by asim-shrestha** [comment]
Added support for a custom base path through ENV: https://github.com/reworkd/AgentGPT/pull/543
