### ISSUE TITLE
Build Fails on New Updates to the Repo 

### ISSUE THREAD

**Issue by rossman22590** [reworkd/AgentGPT#490]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

It builds properly 

### Current behaviour

ERROR: 

<html>
<body>

Type error: Type '{ icon: Element; name: string; onChange: () => null; items: Element[]; styleClass: { container: string; input: string; option: string; }; }' is not assignable to type 'IntrinsicAttributes & MenuProps'.
--
12:11:54.359 | Property 'onChange' does not exist on type 'IntrinsicAttributes & MenuProps'.
12:11:54.359 |  
12:11:54.359 | 377 \|         icon={<CgExport />}
12:11:54.359 | 378 \|         name={`${t("EXPORT", { ns: "common" })}`}
12:11:54.359 | > 379 \|         onChange={() => null}
12:11:54.359 | \|         ^
12:11:54.360 | 380 \|         items={exportOptions}
12:11:54.360 | 381 \|         styleClass={{
12:11:54.360 | 382 \|           container: "relative",
12:11:54.433 | Error: Command "npm run build" exited with 1
12:11:55.211 | Deployment completed
12:11:54.789 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1

</body>
</html>

### Steps to reproduce

Build on Vercel

### Possible solution

not too sure here , it was working as of last nights commits

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by asim-shrestha** [comment]
Hey apologies, should be fixed now
