### ISSUE TITLE
💬 the "copy" button in the chat-window should change to "copied" on clicking

### ISSUE THREAD

**Issue by prathamjagga** [reworkd/AgentGPT#50]
The button copies the conversation, but to let the users know it is successfully copied, the copy button should change to coped.
![image](https://user-images.githubusercontent.com/30550632/231465438-700ffd05-0f26-4c69-91c5-42b6ea078fcb.png)

**Comment by hahayusuf** [comment]
Will submit a PR for this soon!

**Comment by hahayusuf** [comment]
I have created a pull request for this

https://github.com/reworkd/AgentGPT/pull/52
