### ISSUE TITLE
Invalid environment variables: NEXT_PUBLIC_BACKEND_URL: Required

### ISSUE THREAD

**Issue by SnoopyDevelops** [reworkd/AgentGPT#508]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

The setup script should be run without problem.

### Current behaviour

![image](https://github.com/reworkd/AgentGPT/assets/54778084/616f2e05-9004-4e3d-bc0f-231601006e3a)

### Steps to reproduce

1. Create a new Codespace.
2. run `bash ./setup.sh --local` in terminal.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by linghongli** [comment]
Same question

**Comment by tom-dell** [comment]
Could you try setting a environment variable to the one found in .env.example? 

`export NEXT_PUBLIC_BACKEND_URL=http://localhost:3000`

Or maybe appending it to /workspaces/agentgpt/next/.env

**Comment by SnoopyDevelops** [comment]
Added NEXT_PUBLIC_BACKEND_URL in the environment variable section of setup.sh, then it fixed the error

**Comment by asim-shrestha** [comment]
Thanks @SnoopyDevelops !
