### ISSUE TITLE
⌨ More Settings

### ISSUE THREAD

**Issue by OVAWARE** [reworkd/AgentGPT#53]
The Limited Settings limit the capabilities of the AI. To improve this, I suggest adding additional settings, especially when combined with a custom key provided by the user. These settings could include:

- Model
- Loop Limit
- Temperature

These settings can be changed locally, but this would also be beneficial for the web UI in general.

**Comment by asim-shrestha** [comment]
Hey we're working on model and can definitely add temperature. Loop limit was tricky since costs to execute a large number of loops on the server are high, might be possible now. @jshen123 is working on this

**Comment by asim-shrestha** [comment]
This has since been completed :) 

![image](https://user-images.githubusercontent.com/50181239/236127841-0b6df557-992a-4aa8-81c2-d681e8974b41.png)


Appreciate the input!
