### ISSUE TITLE
Due to costs, we've had to momentarily disable web search

### ISSUE THREAD

**Issue by yuis-ice** [reworkd/AgentGPT#533]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

I don't understand why it is not available when it is self hosted so it must be able to browse the web freely. 

### Current behaviour

Due to costs, we've had to momentarily disable web search

### Steps to reproduce

./setup.sh --docker-compose
Then, localhost:3000
Then, click Web Search to try to toggle, and the error

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [x] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by richstav** [comment]
Same issue here, not sure if I'm doing something wrong. Using my own api-key, but still same error.

**Comment by yhyu13** [comment]
The setup section is readme said to set NEXT_PUBLIC_WEB_SEARCH_ENABLED=true to .env and use you own serp API key for the web search

**Comment by linghongli** [comment]
<img width="960" alt="image" src="https://github.com/reworkd/AgentGPT/assets/2770205/e5354a7c-df63-49b0-b83d-396cd738e556">
![image](https://github.com/reworkd/AgentGPT/assets/2770205/5c2d64f4-400c-4407-a1de-1f9f4280c6ad)


I have set it to true and configured the key, but clicking Start on the UI still prompts that it cannot be used

**Comment by linghongli** [comment]
@yhyu13

**Comment by linghongli** [comment]
> <img alt="image" width="960" src="https://user-images.githubusercontent.com/2770205/239166176-e5354a7c-df63-49b0-b83d-396cd738e556.png">
> ![image](https://user-images.githubusercontent.com/2770205/239166417-732cf772-a20b-4d25-aafe-f3e19919dfec.png)
> 
> I have set it to true and configured the key, but clicking Start on the UI still prompts that it cannot be used

@yhyu13 Do you know what the reason is

**Comment by 23557661** [comment]
> 

同样问题，无法使用Web

**Comment by jasangill1** [comment]
Hello @linghongli @23557661 @yhyu13 @richstav please make sure to provide a serper api key if you are using locally, along with updating it in the .env file. The API key can be found here: https://serper.dev/

**Comment by asim-shrestha** [comment]
Furthermore, we've removed this message from the site! Closing now
