### ISSUE TITLE
Deployment fails on vercel although all env provided

### ISSUE THREAD

**Issue by faddy19** [reworkd/AgentGPT#534]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

Expected behavior is a running app on vercel. 

### Current behaviour

<img width="551" alt="Bildschirm­foto 2023-05-12 um 23 26 46" src="https://github.com/reworkd/AgentGPT/assets/51141314/12aac48f-a0c1-4bb0-8ce5-f367623d6e8b">

After providing the env variables it shows a 404 error. 

### Steps to reproduce

Go to vercel app.

Search for the agentgpt template

Click on deploy

enter the env variables

click on deploy

error 404 is showing. 

### Possible solution

I tried it with mysql database but got the same issue. 

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by asim-shrestha** [comment]
@faddy19 it seems your deployment is not finding the project. Please note that we have recently moved to a sub folder and thus you must change your Vercel configurations accordingly

**Comment by rsingh888** [comment]
which configuration to change in vercel?

**Comment by rsingh888** [comment]
nevermind sorted, rather than root next folder should be deployed

**Comment by rsingh888** [comment]
yes solved,
Deploy from next folder rather than root foder
