### ISSUE TITLE
Doesn't run AgentGPT on server it shows simply files after make build on local and upload through AWS EC2

### ISSUE THREAD

**Issue by hashteam2013** [reworkd/AgentGPT#538]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

Expected behavior is to provide a simple way to run build on server

### Current behaviour

Current behavior is that after uploading build on server isn't running

### Steps to reproduce

1). Setup the project on local PC

2). On local it is running perfectly

3). Created build on local by npm run build 

4). Uploaded this build on Amazon AWS EC2

5). it is showing simply uploaded files not the AgentGPT window

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [x] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by jasangill1** [comment]
Hello @hashteam2013 Would you care to explain this problem further so that we can assist you in making this work!! If you could provide us with some log information or any error messages this would help greatly in aiding you!!

Looking forward from hearing back from you !!

**Comment by jasangill1** [comment]
Hello @hashteam2013 Would you be able to run the application through docker? And I assume you only deployed the backend on AWS. Have you tried deploying frontend on Vercel?? I will be closing this thread due to inactivity please feel free to reopen if you would like to discuss further!!
