### ISSUE TITLE
PDF output does not support Chinese/Japanese characters

### ISSUE THREAD

**Issue by enjuichang** [reworkd/AgentGPT#541]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

Exporting as PDF should return details of all tasks.

### Current behaviour

Currently the export does not support chinese/japanese characters at all.  The doc characters are replaced as a crossed box.

[test.pdf](https://github.com/reworkd/AgentGPT/files/11481183/test.pdf)
[test-jp.pdf](https://github.com/reworkd/AgentGPT/files/11481182/test-jp.pdf)

### Steps to reproduce

1. Change the language to Chinese
2. Put in "讓世界變更好" for Chinese or "世界をよりいい場所する" for Japanese in the goal
3. Click on deploy
4. Stop the agent and export as pdf

### Possible solution

It could be due to the export setting's encoding but I have not taken a look at the export methods.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by enjuichang** [comment]
@Cs4K1Sr4C Do you have any clue why it doesn't work? Korean seems to be working fine.

**Comment by Cs4K1Sr4C** [comment]
@enjuichang These are my results:

![image](https://github.com/reworkd/AgentGPT/assets/126985144/ee17126f-5d9e-4b7e-b5ec-4e20173aa95f)

![image](https://github.com/reworkd/AgentGPT/assets/126985144/3d62b223-a124-4a14-a17b-0d7886b6e04d)

**Comment by enjuichang** [comment]
Oh got it! Maybe it's a mac problem i'll do some more research

**Comment by Cs4K1Sr4C** [comment]
Thank you, I'm waiting for the results. Tomorrow I'll install a macOS on virtual and after I can follow you and others on mac.

**Comment by Cs4K1Sr4C** [comment]
@enjuichang Any results on this from your side? It would be great if you can send a feedback about your research. FYI: I had no problem on my buddy's MacBook.

**Comment by enjuichang** [comment]
Hey @Cs4K1Sr4C still not sure why my computer cant process it... I've been MIA for the past week. I've tested out other MacBooks and it seems like it's working fine. Could be an M1/intel difference. I'll update you when I have more info!

**Comment by enjuichang** [comment]
@Cs4K1Sr4C Also curious about the mapping process from text to translations. I saw you open a PR about google translating the text automatically. With the recent updates on AgentGPT, is there a need for someone to map each new text into a key somewhere? let me know if that's needed.

**Comment by Cs4K1Sr4C** [comment]
Hey @enjuichang, I'm just wondering about your computer... Unfortunately I can't reproduce the mentioned issue, so I cant figure it out just to hit my stomach where should be the exact problem. Honestly I don't think so it is related to intel/M1, but everything is possible...  I hope you can use it on other platform or on other device as you need it to use AgentGPT and its export function.

I have started to extend the main object I used at the beginning to translate AgentGPT.
Here you can find more details where it's standing now: [🤖 ATi18n 🌏 ](https://github.com/Cs4K1Sr4C/ATi18n)

The Google translation method is a free solution to translate the already mapped key/value pairs, but if you have the OpenAI as the translator service then only default text is enough and it will change the source code, replace the `default_text` with key suggestion and namespace suggestion by the filename.

**Comment by jasangill1** [comment]
Hello @enjuichang How are you !!!

Are you still experiencing this problem!!

**Comment by enjuichang** [comment]
Unfortunately so! I really don't know why! I will try to translate more of AgentGPT later this week tho!
