### ISSUE TITLE
OpenAI API & Serp API fetch does not support proxy server yet for beta 0.4.0

### ISSUE THREAD

**Issue by yhyu13** [reworkd/AgentGPT#549]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/reworkd/AgentGPT/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/reworkd/AgentGPT/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

For the beta 0.4.0 release, it seems openai and serp web search do not support proxy anymore. The previous release v0.3 seems fine.

```
HTTP_PROXY=xxx
HTTPS_PROXY=xxx
```

### ✔️ Solution

I am not sure what changes has made to open ai API call.

For Serp.ts, we should be able to fetch through proxy agent like this 

```
async callSerper(input: string) {
  const HttpsProxyAgent = require('https-proxy-agent');
  const proxyAgent = new HttpsProxyAgent('http://your-proxy-server-url.com:port');
  
  const options = {
    method: "POST",
    headers: {
      "X-API-KEY": this.key,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      q: input,
    }),
    agent: proxyAgent,
  };

  const res = await fetch("https://google.serper.dev/search", options);

  if (!res.ok) {
    console.error(`Got ${res.status} error from serper: ${res.statusText}`);
  }

  return res;
}
```

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by qcgm1978** [comment]
I experienced a connection issue and I'm unsure if it's related to my current problem. Today, after several days, I retrieved the project and encountered multiple conflicts. To resolve them, I accepted all incoming changes. However, upon running 'npm run dev', an error message appeared stating 'ERROR accessing OpenAI's API. Please check your API key or try again later'. Previously, this project ran without any issues. I am uncertain about what went wrong - is this project no longer supporting free OpenAI keys? Or is my proxy invalid? Additionally, where should I configure network access proxies as my network cannot directly connect to OpenAI?

**Comment by asim-shrestha** [comment]
@yhyu13 We haven't changed anything on our end that would affect the use of those proxies (though this is not something we actively test / support) Unfortunately this would have to be something taken up with OpenAI (Though I do know there are other proxy services that will forward your OpenAI call

@qcgm1978 yeah we have been undergoing a lot of refactoring and changes. In production we cannot really support free tier keys anymore but running locally it should be fine. One thing to note however is that OpenAI may have reduced their rate limits for the free tier, causing more errors to be met or they may have disallowed whatever proxies you are using. Unfortunately not something we can help with directly, but please do update us if you find a solution

**Comment by yhyu13** [comment]
@ALL
I've succeeded using socks5 protocol getting both OpenAI and serp fetch working behind a proxy. You can modify the setup script like this : https://github.com/yhyu13/AgentGPT/commit/91e79325ce29a8bd820bfda28ace0c48a443549f
