### ISSUE TITLE
Serp Search

### ISSUE THREAD

**Issue by rossman22590** [reworkd/AgentGPT#568]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

The web search works after key is put

### Current behaviour

does not use key doe not search

### Steps to reproduce

go to the app
do web search

### Possible solution

what website does key come form, there are two with similar names. 

### Which Operating Systems are you using?

- [X] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by rossman22590** [comment]
getting vercel error: [POST] /api/agent/execute
Got 403 error from serper: Forbidden

**Comment by rossman22590** [comment]
is this fixed? and is this the right api? https://serpapi.com/dashboard

**Comment by asim-shrestha** [comment]
Hey no, seems to be an api key issue since you're using the wrong platform

The correct one is: https://serper.dev/

**Comment by asim-shrestha** [comment]
Hey no, seems to be an api key issue since you're using the wrong platform

The correct one is: https://serper.dev/

**Comment by yf007** [comment]
> 
Still the same error/glitch

**Comment by yf007** [comment]
> Hey no, seems to be an api key issue since you're using the wrong platform
> 
> The correct one is: https://serper.dev/

Still the same error/glitch

**Comment by asim-shrestha** [comment]
Hey folks, we've updated our setup scripts. Can you please fetch the latest changes from main and re-run `./setup.sh`

**Comment by jasangill1** [comment]
Hello everyone, 👋

Is anyone still experiencing this problem? if so try these steps 

In light of the recent changes, we request everyone facing this issue to fetch the latest changes from the main branch and re-run `./setup.sh` or `./setup.bat`. 

@rossman22590, @yf007, could you please let us know if you're still encountering this problem after running the setup script again?

We appreciate your patience and cooperation in this matter. Looking forward to hearing from you! 🙌

**Comment by jasangill1** [comment]
closed due to inactivity and duplicate issues like this that are still open https://github.com/reworkd/AgentGPT/issues/892!!
