### ISSUE TITLE
📄 Some output text is truncated

### ISSUE THREAD

**Issue by llagerlof** [reworkd/AgentGPT#57]
I installed the version from the main branch, commit 06e781e0d6f63ca6560f92e408f09d295b17235b

I asked for some HTML with some content (not important), but the HTML being generated is truncated.

The truncated part is not even that big. The first test the agent output ~400 bytes. In other test, ~800 bytes, always truncated.

 Is there a size limit for the output? Any way to increase the size limit?

**Comment by asim-shrestha** [comment]
Hey we currently have a token limit in place to save on costs (Can't support current scale with full token sizes) Look to future updates to remove this

**Comment by asim-shrestha** [comment]
Hey there, now if you use your own API key you are able to configure the token length. In the future we will offer a subscription service to allow for increased token lengths as well.
