### ISSUE TITLE
Error accessing OpenAI's Api when trying to add key to agentgpt

### ISSUE THREAD

**Issue by Oranejohnson** [reworkd/AgentGPT#571]
Im receiving this error when i try to deploy an agent.
I have a paid account but still receive this error
am i doing something wrong
<img width="748" alt="image" src="https://github.com/reworkd/AgentGPT/assets/46091581/8e5edcda-8d52-4829-bfe1-2c711d903e18">
<img width="748" alt="Screenshot 2023-05-22 131420" src="https://github.com/reworkd/AgentGPT/assets/46091581/d02d5a95-ba5f-4f9b-a362-93155770307e">

**Comment by asim-shrestha** [comment]
Have you taken a look at the FAQ? https://docs.reworkd.ai/faq

Can you also attach your .env file here?

And are you running through docker?

**Comment by Oranejohnson** [comment]
is there a walk-through gaudier? I am not sure how to get the env. file. - I'm using the web version- and i think i have paid api key account

**Comment by asim-shrestha** [comment]
Gotcha, based on recurring issues we've actually removed this option :( 

You are however free to run the tool locally. We'll have a better walk through setup guide in the future.
