### ISSUE TITLE
AgentGPT stuck at Searching web for " some topic here " for long and does not progress

### ISSUE THREAD

**Issue by munish0838** [reworkd/AgentGPT#580]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

Should search/ not search web based on tool is allowed or not and return answer quickly

### Current behaviour

Stuck at searching web for more than 25 min now and does not progress further

### Steps to reproduce

Current web version,
Add a name and prompt that needs web search

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by MissGorgeousTech** [comment]
happened to me also

**Comment by Ayo-faks** [comment]
happening to me also

**Comment by asim-shrestha** [comment]
@munish0838 @MissGorgeousTech @Ayo-faks 

We had some issues with agents getting stuck before and with bad error messages causing exceptions to freeze the app. We've since worked to resolve this. Are you still getting this?

**Comment by pedrohfw** [comment]
Good afternoon, 

I'm having the same problem.

AgentGPT is stuck on "Completing: Identify reliable sources on the Brazilian Penal Law and its timeline."

**Comment by jasangill1** [comment]
Hello @munish0838 @MissGorgeousTech @Ayo-faks @pedrohfw Are you guys still experiencing this problem after the recent updates?

**Comment by asim-shrestha** [comment]
Maybe worth clearing cookies / cache on your browser or trying in incognito

**Comment by pedrohfw** [comment]
> Hello @munish0838 @MissGorgeousTech @Ayo-faks @pedrohfw Are you guys still experiencing this problem after the recent updates?

good morning @jasangill1 , it's solved for me!

**Comment by jasangill1** [comment]
@pedrohfw Thanks for confirming and replying !! I will be closing this form as the problem has been solved!! Feel free to reopen if still experiencing these problems
