### ISSUE TITLE
🐳 Update setup scripts

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#584]
The old setup script does not work correctly with our new infrastructure configuration.

We should use a tool like commander to automatically get the required env values and generate the correct env. We should remove the .env.example all together and rely on this tool. 

It should be able to configure the ENV dynamically based on whether or not you are using docker. It should tell you the next steps after the script has run based on what you are trying to use. 

Ideally, the script should know if you already have an env with specific values like an open ai key and ignore it accordingly

**Comment by linghongli** [comment]
very important

**Comment by asim-shrestha** [comment]
@linghongli this has now been competed! 

#611
