### ISSUE TITLE
Could this be made to work solely on the client (browser)?

### ISSUE THREAD

**Issue by waldenn** [reworkd/AgentGPT#59]
I'm currently using a ChatGPT client[*](https://github.com/xqdoo00o/chatgpt-web) which is completely functional in the browser, and the users OpenAI key is only stored in the browser's local-storage database. This setup allows other people to use their own key with the AI tool.

It would be great to see this project work in that mode too. I understand there could be CORS issues, but sometimes all you need for that is a JSON-proxy. Thanks for this interesting project!

**Comment by OVAWARE** [comment]
You mean [agentgpt.reworkd.ai](https://agentgpt.reworkd.ai/) ?

**Comment by waldenn** [comment]
Ah yes! I looked at the Github docs and it told me about storing the key in an environment file. So this mode is already functional I gather?
