### ISSUE TITLE
Unhandled Closed Connection w/Streaming

### ISSUE THREAD

**Issue by awtkns** [reworkd/AgentGPT#643]
https://github.com/ajndkr/lanarky/issues/76#issue-1733489956

> Recently we merged some changes into https://github.com/reworkd/AgentGPT/pull/631 which enabled streaming on AgentGPT > using lanarky!
> After merging, I noticed an increase error rate due to what I assume is lanarky not closing the connection to openai if the client (React in our cases) closes the SSE stream early. This happens, for example, when the user closes the page while in the middle of a chat completion being streamed.

AC: Bump lanarky to verify streaming is fixed

**Comment by awtkns** [comment]
fix in #644

**Comment by jasangill1** [comment]
Closing as fix was merged!
