### ISSUE TITLE
🗯 Running locally, keeps asking for API key

### ISSUE THREAD

**Issue by harnoor-saini** [reworkd/AgentGPT#65]
Hello, I am running on localhost but it keeps asking for my API key. Is that expected behaviour?

**Comment by carlaiau** [comment]
Same here

**Comment by astelmach01** [comment]
It should not be, I'll work on a fix and submit a PR today or tomorrow

**Comment by astelmach01** [comment]
https://github.com/reworkd/AgentGPT/pull/67

**Comment by gauravsaini** [comment]
Why not just set OPENAI_API_KEY as empty key in env file . Wouldn't that do the trick ? (just asking)

**Comment by astelmach01** [comment]
How would an empty key fix anything?

**Comment by asim-shrestha** [comment]
Heyo! Yeah functionality will be catered to the product side most often - leading to some dev annoyances like this, sounds like we have a fix in though!

**Comment by awtkns** [comment]
This is fixed in main :)

**Comment by xunjianxiang** [comment]
Same situation!
I have pulled the latest.
[commit id] 13ea8bf661bbc0cba11e8717d41afdf75964fa61
