### ISSUE TITLE
Need help with AgentGPT Docker update: "There was an issue getting a response from the AI model"

### ISSUE THREAD

**Issue by 8088boy** [reworkd/AgentGPT#653]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

I recently updated AgentGPT via Docker, and I'm encountering an issue where it keeps showing the error message "There was an issue getting a response from the AI model." I've tried several troubleshooting steps, but I haven't been able to resolve the problem. 

### Current behaviour

Stop running with a error "There was an issue getting a response from the AI model"

### Steps to reproduce

1.Pulled the latest changes from the Git repository.
2.Ran docker-compose up --build to rebuild the Docker containers.
3.Updated the OPEN_API_KEY value in ./next/.env file.
4.Started the AgentGPT service in Docker.
5.Opened localhost:3000 in my browser and deployed the agent after entering all the information and settings. 

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [x] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by maboali** [comment]
I got the same issue but when I checked the error log from the docker container console I found out that the API sent me an error regarding my subscription status

reworkd_platform.web.api.errors.OpenAIError: The model: `gpt-4` does not exist
platform             | 2023-06-03 15:04:18.230 | INFO     | logging:callHandlers:1706 - 172.18.0.1:60714 - "POST /api/agent/start HTTP/1.1" 409
platform             | 2023-06-03 15:04:31.676 | INFO     | logging:callHandlers:1706 - message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=None request_id=a8964e210f4855452a6d0faa114973dd response_code=429
platform             | 2023-06-03 15:04:31.677 | INFO     | logging:callHandlers:1706 - error_code=None error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
platform             | 2023-06-03 15:04:31.677 | WARNING  | logging:callHandlers:1706 - Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
platform             | 2023-06-03 15:04:35.272 | INFO     | logging:callHandlers:1706 - message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=None request_id=842a309287ad60d45d38e56b7d2d3791 response_code=429
platform             | 2023-06-03 15:04:35.272 | INFO     | logging:callHandlers:1706 - error_code=None error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
platform             | 2023-06-03 15:04:35.273 | WARNING  | logging:callHandlers:1706 - Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 2.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
platform             | 2023-06-03 15:04:37.552 | INFO     | logging:callHandlers:1706 - message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=None request_id=2de085c4f259830fe20dd7dcf7e00b93 response_code=429
platform             | 2023-06-03 15:04:37.552 | INFO     | logging:callHandlers:1706 - error_code=None error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
platform             | 2023-06-03 15:04:37.553 | WARNING  | logging:callHandlers:1706 - Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
platform             | 2023-06-03 15:04:41.926 | INFO     | logging:callHandlers:1706 - message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=None request_id=15f0b387d27ed234cdada1d3fa941411 response_code=429
platform             | 2023-06-03 15:04:41.927 | INFO     | logging:callHandlers:1706 - error_code=None error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
platform             | 2023-06-03 15:04:41.929 | WARNING  | logging:callHandlers:1706 - Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
platform             | 2023-06-03 15:04:50.624 | INFO     | logging:callHandlers:1706 - message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=None request_id=91eff1782e25eab777a676f1e1b5acae response_code=429
platform             | 2023-06-03 15:04:50.625 | INFO     | logging:callHandlers:1706 - error_code=None error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
platform             | 2023-06-03 15:04:50.625 | WARNING  | logging:callHandlers:1706 - Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 16.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
platform             | 2023-06-03 15:05:07.674 | INFO     | logging:callHandlers:1706 - message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=None request_id=5231b2f0da84b4b7e19abbf6c96287c3 response_code=429
platform             | 2023-06-03 15:05:07.674 | INFO     | logging:callHandlers:1706 - error_code=None error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
platform             | 2023-06-03 15:05:07.675 | ERROR    | reworkd_platform.web.api.error_handling:platformatic_exception_handler:12 - You exceeded your current quota, please check your plan and billing details.

**Comment by 8088boy** [comment]
Thanks for reply. 
Yes, I had the API error in the log, but the OpenAI KEY was working before I updated and also working for autogpt while I am posting here. I can't find more details with the error message it like in your case. 

```
2023-06-03 11:45:37 platform             | 2023-06-03 18:45:37.857 | INFO     | logging:callHandlers:1706 - error_code=invalid_api_key error_message= error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
```
The full log file : https://pastebin.com/XKA5uLbJ

I wonder what else params I missed in the AgentGPT/next/.env file
![image](https://github.com/reworkd/AgentGPT/assets/95098546/990400cc-8cd6-440a-98ac-da7e4e47f2f0)
