### ISSUE TITLE
Doesn't stop when it should

### ISSUE THREAD

**Issue by astelmach01** [reworkd/AgentGPT#66]
The agent doesn't stop when it should (it has completed and no new tasks added)

![element-image (1)](https://user-images.githubusercontent.com/58709763/231613619-bc73b9b1-d0b4-4785-84e7-edd5f000e686.png)

**Comment by yourepicservices** [comment]
Looks like #75 has been merged. @astelmach01 do you have any input on this or can we consider this resolved?

**Comment by asim-shrestha** [comment]
The above case won't occur anymore but there could be different wordings of this that might lead to the same error. Closing for now but can revisit if this occurs
