### ISSUE TITLE
🚨 Apply for OpenAI Azure endpoints

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#680]
Azure endpoints apparently run a lot quicker than OpenAI's. We should try and support them, especially given the demand for this seems relatively high.

First up is applying for access!

**Comment by asim-shrestha** [comment]
Lots of demand for this here: https://github.com/reworkd/AgentGPT/issues/77

After this is completed, we should mention it in the issue above and tag everyone that was looking to use this

**Comment by Zizico2** [comment]
I'd like to tackle this. Can anyone provide any guidance, or should I dive straight in?

**Comment by asim-shrestha** [comment]
Ah @Zizico2, this is just applying for the credits haha 😂. We do still need to be able to support it on our platform however. 

If you'd like to integrate functionality to enable azure open ai (Perhaps through ENV first) please do so! We create the model early on within FastAPI. Heres some docs that might help: https://python.langchain.com/docs/modules/model_io/models/llms/integrations/azure_openai_example

**Comment by VectorZhao** [comment]
What is the current progress?

**Comment by qkxie** [comment]
need azure support, too

**Comment by Zizico2** [comment]
@VectorZhao @qkxie https://github.com/reworkd/AgentGPT/issues/77#issuecomment-1655942049

**Comment by awtkns** [comment]
fixed in #1165
