### ISSUE TITLE
🧠 Remove "Thinking" messages

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#686]
The "Thinking" messages add a lot of bloat to the output. We should instead use a spinner while loading / waiting for a response from the backend.

**Comment by abhithory** [comment]
@asim-shrestha , can you asign me this issue? i want to work on this

**Comment by jasangill1** [comment]
task completed!

**Comment by asim-shrestha** [comment]
Hey sorry @abhithory , this is actually already done
