### ISSUE TITLE
readme error

### ISSUE THREAD

**Issue by iplayfast** [reworkd/AgentGPT#7]
The readme instructions should also include the instruction to cd AgentGPT

**Comment by awtkns** [comment]
Thanks for reporting this @iplayfast! 

This issue is up for grabs for whomever wants it!

**Comment by hahayusuf** [comment]
> Thanks for reporting this @iplayfast! 
> 
> 
> 
> This issue is up for grabs for whomever wants it!

Hi @awtkns 

Would love to do this. Have some experience with CD for TS projects.

**Comment by awtkns** [comment]
@hahayusuf its yours for the taking if you want 😊

**Comment by ghost-2362003** [comment]
i want it

**Comment by awtkns** [comment]
Anyone is welcome to create a pr
