### ISSUE TITLE
✨ Add a copy button to the header of the execute tasks window

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#707]
As a user, I'd like to be able to copy the output of an individual cell directly. We should add a copy button to the top right of chat messages

**Comment by abhithory** [comment]
@asim-shrestha hi. I am really interested to work on this

**Comment by abhithory** [comment]
@asim-shrestha , can you please assign me this issue? i want to work on this. and also let me know should i add button according to this image in above comment?

**Comment by abhithory** [comment]
@asim-shrestha , can you please assign me this issue? i want to work on this. and also let me know should i add button according to this image in above comment?

**Comment by jasangill1** [comment]
Hello @abhithory Love the work ethic!! we actually just completed this task yesterday feel free to private message me on discord if you want a more personal role and assignments!!

**Comment by abhithory** [comment]
ok @jasangill1 ,  I just messaged you please check.

**Comment by abhithory** [comment]
hello @jasangill1 , `Json` `namesnipe` is your username on discord. right? 

i just messaged you there
