### ISSUE TITLE
Deploy in vercel

### ISSUE THREAD

**Issue by johnfelipe** [reworkd/AgentGPT#715]
### What piece of documentation is affected?

Is not created

### What part(s) of the article would you like to see updated?

How deploy in vercel

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by johnfelipe** [comment]
Anyone?

**Comment by jasangill1** [comment]
Hello @johnfelipe I would love to help, could you please provide me with any screenshots of your problem to get a better understanding? what part of deploying are you having trouble with?

**Comment by johnfelipe** [comment]
I want to deploy in vercel, can u add button in readme file and docs or steps for do it?

**Comment by jasangill1** [comment]
Hello @johnfelipe We are currently in the process of updating our docs!! Ill make an issue to remind us to make this for users!!!

**Comment by johnfelipe** [comment]
Will be a good feature, running in vercel and review all changes in sync repo
I hope don't forget this request
Tnks

**Comment by jasangill1** [comment]
Hello @johnfelipe for all updates on this issue visit the new issue forum here: https://github.com/reworkd/AgentGPT/issues/975

!!!

**Comment by jasangill1** [comment]
Will be closing as new ticket created!!!
