### ISSUE TITLE
Use Github Actions

### ISSUE THREAD

**Issue by astelmach01** [reworkd/AgentGPT#73]
Instead of needing to wait for approval, automatically test + deploy with GA (unless it's too expensive on vercel idk those details)

https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

**Comment by asim-shrestha** [comment]
So with vercel deployments, a bad actor could produce a PR that can expose our preview API keys which is not ideal 

CC @awtkns

**Comment by asim-shrestha** [comment]
Going to close because of the above ^
