### ISSUE TITLE
🌗 Add button to toggle colour options dark mode

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#746]
We should support dark mode programatically through tailwind. Below is some documentation that outlines this.

https://tailwindcss.com/docs/dark-mode

We should respect user theme preference but save any preference overrides to local storage to reference later, as defined in the `Supporting system preference and manual selection` of the document. There should be some button either on the drawer or on the user settings that can toggle between the options.

**Comment by jasangill1** [comment]
Button added !! Closing as the button was added and not just integrating the changes to individual components
