### ISSUE TITLE
⬇️ Add a scroll down button to the ChatWindow

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#748]
When the chat window has scrolled far enough up like below:
![Image](https://github.com/reworkd/AgentGPT/assets/50181239/9f6ba72c-d64e-4033-8fbc-b05a9c4f2988)

We should add a button at the bottom right that when clicked, will scroll to the bottom of the chat window so that users can quickly see the new outputs
![Image](https://github.com/reworkd/AgentGPT/assets/50181239/f26c4a3a-c1e3-4928-9460-467014432cfb)

**Comment by lyqht** [comment]
can i try working on this?

**Comment by asim-shrestha** [comment]
@lyqht Yes! Added you as the assignee

**Comment by ajay2827** [comment]
@asim-shrestha I am interested in this, can you assign it to me?

**Comment by asim-shrestha** [comment]
Feel free to give it a go too!

**Comment by asim-shrestha** [comment]
Feel free to give it a go too!

**Comment by lyqht** [comment]
I'll let Ajay work on it then, since I haven't started on it. prefer not to do duplicate work

**Comment by abhithory** [comment]
@ajay2827  are you working on this?? because i am also interested to work on this. so if you are not working then let me know

**Comment by ajay2827** [comment]
> @ajay2827 are you working on this?? because i am also interested to work on this. so if you are not working then let me know

i am working on this , you may work work on other issue

**Comment by ajay2827** [comment]
@asim-shrestha can you help me set it up locally, I am trying to setup using docker-compose but it shows, can you provide some resources, as a beginner to open source it is my first repo ,

**Comment by abhithory** [comment]
@ajay2827 , i have successfully set up and run the project locally. I can help you if you want.

can you share what error are you getting? or do you want each step to run project locally?

**Comment by ajay2827** [comment]
> @ajay2827 , i have successfully set up and run the project locally. I can help you if you want.
> 
> can you share what error are you getting? or do you want each step to run project locally?

Thank you for helping me out,  can you provide each step to run a project locally, please?

**Comment by abhithory** [comment]
ok cool

- Fork this repo in your own GitHub account 
- then Clone the forked repo of AgentGPT  in your pc ( git clone https://github.com/YOUR-GITHUB-USERNAME/AgentGPT.git )
- then open the terminal in the cloned repo folder
- install and run docker in your computer

- in the terminal then run the setup script
Mac/Linux -> ./setup.sh
windows -> setup.bat

- then choose docker-compose option
- Go to openAi, serb, replicate website. Create your account and get your api key
- paste these api keys in the setup process

- first time it will take some time
- then finally you will see Nextjs running

**Comment by abhithory** [comment]
ok cool @ajay2827 

- Fork this repo in your own GitHub account 
- then Clone the forked repo of AgentGPT  in your pc ( git clone https://github.com/YOUR-GITHUB-USERNAME/AgentGPT.git )
- then open the terminal in the cloned repo folder
- install and run docker in your computer

- in the terminal then run the setup script
Mac/Linux -> ./setup.sh
windows -> setup.bat

- then choose docker-compose option
- Go to openAi, serb, replicate website. Create your account and get your api key
- paste these api keys in the setup process

- first time it will take some time
- then finally you will see Nextjs running

**Comment by asim-shrestha** [comment]
We have guides on the README and docs: https://docs.reworkd.ai/development/setup

Let me know if there are issues here

**Comment by abhithory** [comment]
@jasangill1, I can fix this issue. but @ajay2827 was working on this that's why i have not started working on this yet.

so, now if @ajay2827 is not working on this so should i work on this?

**Comment by jasangill1** [comment]
Hello @abhithory yeah that works I will assign this to you! I can't wait to see what you have in store. Also, feel free to reach out in regards to any problems you may come across

**Comment by abhithory** [comment]
@jasangill1 ok thanks

**Comment by abhithory** [comment]
hi @jasangill1 , do you know any way to get free openai api credit? 
I have created new account but there is no free credit....

and in agentgpt it is showing 
![image](https://github.com/reworkd/AgentGPT/assets/76877003/efdc473b-487f-4bb1-8f52-bb19ec7a765d)

**Comment by abhithory** [comment]
Hello @jasangill1 @asim-shrestha , I have added the scroll to the bottom button with smooth fade animation. Please check is it what you want. 

=> Should i make PR with this ?? or is there something else to improve in this??

=> Here I have added Dummy message  data for testing because i don't have credits in openAi Api so thats why i can't test with that. 


https://github.com/reworkd/AgentGPT/assets/76877003/c45a421d-7d91-4bac-a2bc-36deb5d0cff9

**Comment by abhithory** [comment]
also, i can add a scroll to the top button when the user is at bottom of the chat.... Please let me know  if it's needed?

**Comment by asim-shrestha** [comment]
@abhithory Nice! Lets make a PR for that. 

- I think OpenAI can tell when you make new accounts on the same device and won't issue you free credits (Or they stopped entirely). 
- We don't need a scroll to top

**Comment by abhithory** [comment]
@asim-shrestha , is this what you want??

https://github.com/reworkd/AgentGPT/assets/76877003/31266f70-151c-4354-a70b-4bccc4ef864a

- I also find one thing. I think this is a typo. should I correct it?


![typo](https://github.com/reworkd/AgentGPT/assets/76877003/3c299f6f-ac32-40a9-bba7-d0bc4b7981a2)
1962aa8-6bb4-45c7-9bd1-cf4caf812a97

**Comment by jasangill1** [comment]
Hello @abhithory I love seeing the hard work and responsiveness man keep up the good work!!!!

**Comment by abhithory** [comment]
Thank you very much @jasangill1 for your kind words. you are very nice.

**Comment by abhithory** [comment]
@asim-shrestha @jasangill1 , i have created PR for this. please check that. and let me know if there is any improvement or change

**Comment by jasangill1** [comment]
Hello @abhithory no problem, here at reworkd we believe that hard work always deserves recognition!!! While we wait for asim to review would you mind starting on the other issues assigned to you!! This would be a huge help. 

Remember we are always here to help feel free

**Comment by asim-shrestha** [comment]
That looks perfect! And feel free to update the typo 

Thanks @abhithory

**Comment by abhithory** [comment]
Yes sure @jasangill1 , i will work on other issue now

**Comment by jasangill1** [comment]
Hello, @abhithory I will be closing as it seems the tasks is completed. Greate work!! Excited to see what more you have instore!!!

**Comment by abhithory** [comment]
@jasangill1 thanks
