### ISSUE TITLE
API Endpoint: 404 error

### ISSUE THREAD

**Issue by liferadioat** [reworkd/AgentGPT#752]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

When using nginx as proxy server the api endpoint should be reachable

`        location ^~ /api {
                proxy_pass http://localhost:8000;
                proxy_set_header Host $http_host;
        }
`

### Current behaviour

It gives a 404 error since version 0.7.0. It worked with version 0.6.0.

### Steps to reproduce

Start Agengpt with docker compose
Use one different port at docker-compse.yaml: 
`services:
  next:
    container_name: next
    build:
      context: ./next
      dockerfile: Dockerfile
    ports:
      - "3500:3000"
`
Use nginx as proxy server:

`location / {
    proxy_pass http://localhost:3500/;
    proxy_set_header Host $host;
    #proxy_set_header X-Forwarded-Scheme $scheme;
    #proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location ^~ /api {
                proxy_pass http://localhost:8000;
                proxy_set_header Host $http_host;
        }
`
Try to authenticate with click on the word "sign in" at the top left.

### Possible solution

Make clear, how the api endpoint is addressable

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by xiaol** [comment]
I have the same issue too, 
i thought ubunut lack of some information in console.

**Comment by bkkkd** [comment]
I have the same issue too

**Comment by jasangill1** [comment]
@liferadioat  Check if the service at localhost:8000 is running: Since the proxy is supposed to be passing traffic to this service, it would return a 404 if this service is not up and running. Along with try running in production!

**Comment by jasangill1** [comment]
Any luck!! @bkkkd @liferadioat

**Comment by liferadioat** [comment]
Solution was a better nginx config - https://gist.github.com/benhartwich/f6b6bd3715e0a50e66cc4d167c55a587

**Comment by jasangill1** [comment]
@liferadioat Awesome !!!
