### ISSUE TITLE
💅 Update sign-in page

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#766]
We've been using the default sign in page of Next auth

![Image](https://github.com/reworkd/AgentGPT/assets/50181239/7ea51751-e34f-48b9-ac50-2a715ae08e59)

We should instead make our own custom page based on TailwindUI components: https://tailwindui.com/components/application-ui/forms/sign-in-forms. If you don't have this, any similar design would work.

Note that currently, we don't allow for the sign in providers in development mode. You'll need to manually change your NODE_ENV to not be development to see the providers.

**Comment by abhithory** [comment]
hi @asim-shrestha, i would love to work on this. I know all of the things to make this custom page. 

just can you please tell me is there any specific design for this?? or do i just build like next auth with tailwind?

thanks

**Comment by abhithory** [comment]
@asim-shrestha hi

**Comment by abhithory** [comment]
Hi @asim-shrestha , after cloning this repo it is working fine in "development" mode, but when i change "NODE_ENV=production" then it is showing this error.... can you please help me in this?? or is there any other way to work on this in development.??



next                 | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
next                 | info  - Loaded env from /next/.env
platform             | 2023-06-14 03:13:27.930 | INFO     | logging:callHandlers:1706 - Started server process [8]
platform             | 2023-06-14 03:13:27.930 | INFO     | logging:callHandlers:1706 - Waiting for application startup.
platform             | 2023-06-14 03:13:27.941 | ERROR    | logging:callHandlers:1706 - Traceback (most recent call last):
platform             |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
platform             |     async with self.lifespan_context(app) as maybe_state:
platform             |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
platform             |     await self._router.startup()
platform             |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
platform             |     await handler()
platform             |   File "/app/src/reworkd_platform/web/lifetime.py", line 60, in _startup
platform             |     _setup_db(app)
platform             |   File "/app/src/reworkd_platform/web/lifetime.py", line 26, in _setup_db
platform             |     engine = create_engine()
platform             |              ^^^^^^^^^^^^^^^
platform             |   File "/app/src/reworkd_platform/db/utils.py", line 21, in create_engine
platform             |     ssl_context = ssl.create_default_context(cafile=settings.db_ca_path)
platform             |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
platform             |   File "/usr/local/lib/python3.11/ssl.py", line 770, in create_default_context
platform             |     context.load_verify_locations(cafile, capath, cadata)
platform             | FileNotFoundError: [Errno 2] No such file or directory
platform             |
platform             | 2023-06-14 03:13:27.941 | ERROR    | logging:callHandlers:1706 - Application startup failed. Exiting.
platform             | sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=0 mode='r' encoding='UTF-8'>
next                 | event - compiled client and server successfully in 3.7s (357 modules)
next                 | Attention: Next.js now collects completely anonymous telemetry regarding usage.
next                 | This information is used to shape Next.js' roadmap and prioritize features.
next                 | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
next                 | https://nextjs.org/telemetry
next                 |
next                 | wait  - compiling / (client and server)...
next                 | event - compiled client and server successfully in 5.5s (1378 modules)
next                 | wait  - compiling...
next                 | wait  - compiling /_error (client and server)...
next                 | error - src/components/sidebar/links.tsx (7:11) @ FaQuestion
next                 | error - TypeError: (0 , react_jsx_dev_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxDEV) is not a function
next                 |     at eval (webpack-internal:///./src/components/sidebar/links.tsx:16:90)
next                 |     at ./src/components/sidebar/links.tsx (/next/.next/server/pages/index.js:451:1)
next                 |     at __webpack_require__ (/next/.next/server/webpack-runtime.js:33:42)
next                 |     at eval (webpack-internal:///./src/layout/sidebar.tsx:29:84)
next                 |     at __webpack_require__.a (/next/.next/server/webpack-runtime.js:97:13)
next                 |     at eval (webpack-internal:///./src/layout/sidebar.tsx:1:21)
next                 |     at ./src/layout/sidebar.tsx (/next/.next/server/pages/index.js:517:1)
next                 |     at __webpack_require__ (/next/.next/server/webpack-runtime.js:33:42)
next                 |     at eval (webpack-internal:///./src/pages/index.tsx:37:74)
next                 |     at __webpack_require__.a (/next/.next/server/webpack-runtime.js:97:13)
next                 |     at eval (webpack-internal:///./src/pages/index.tsx:1:21)
next                 |     at ./src/pages/index.tsx (/next/.next/server/pages/index.js:528:1)
next                 |     at __webpack_require__ (/next/.next/server/webpack-runtime.js:33:42)
next                 |     at __webpack_exec__ (/next/.next/server/pages/index.js:1317:39)
next                 |     at /next/.next/server/pages/index.js:1318:28
next                 |     at Object.<anonymous> (/next/.next/server/pages/index.js:1321:3)
next                 |     at Module._compile (node:internal/modules/cjs/loader:1275:14)
next                 |     at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
next                 |     at Module.load (node:internal/modules/cjs/loader:1133:32)
next                 |     at Module._load (node:internal/modules/cjs/loader:972:12)
next                 |     at Module.require (node:internal/modules/cjs/loader:1157:19)
next                 |     at require (node:internal/modules/helpers:119:18)
next                 |     at Object.requirePage (/next/node_modules/next/dist/server/require.js:88:12)
next                 |     at /next/node_modules/next/dist/server/load-components.js:48:73
next                 |     at async Object.loadComponents (/next/node_modules/next/dist/server/load-components.js:48:26)
next                 |     at async DevServer.findPageComponents (/next/node_modules/next/dist/server/next-server.js:563:36)
next                 |     at async DevServer.findPageComponents (/next/node_modules/next/dist/server/dev/next-dev-server.js:1041:20)
next                 |     at async DevServer.renderPageComponent (/next/node_modules/next/dist/server/base-server.js:951:24)
next                 |     at async DevServer.renderToResponse (/next/node_modules/next/dist/server/base-server.js:980:32)
next                 |     at async DevServer.pipe (/next/node_modules/next/dist/server/base-server.js:407:25)
next                 |     at async Object.fn (/next/node_modules/next/dist/server/next-server.js:759:21)
next                 |     at async Router.execute (/next/node_modules/next/dist/server/router.js:253:36)
next                 |     at async DevServer.run (/next/node_modules/next/dist/server/base-server.js:384:29)
next                 |     at async DevServer.run (/next/node_modules/next/dist/server/dev/next-dev-server.js:743:20)
next                 |     at async DevServer.handleRequest (/next/node_modules/next/dist/server/base-server.js:322:20) {
next                 |   page: '/'
next                 | }
next                 |    5 |     name: "Help",
next                 |    6 |     href: "https://docs.reworkd.ai/",
next                 | >  7 |     icon: <FaQuestion className="group-hover:text-red-500" />,
next                 |      |           ^
next                 |    8 |   },
next                 |    9 | ];
next                 |   10 |

**Comment by abhithory** [comment]
![image](https://github.com/reworkd/AgentGPT/assets/76877003/fc0d92a6-96a6-4390-a9ea-e37af40f1625)

**Comment by abhithory** [comment]
@asim-shrestha @awtkns 

![image](https://github.com/reworkd/AgentGPT/assets/76877003/9f50d6e3-dcc5-47e2-8157-608ed7f27927)

**Comment by asim-shrestha** [comment]
@abhithory Thanks! Assigned.

Don't change NODE_ENV, just change `NEXT_PUBLIC_VERCEL_ENV` to production otherwise you'll get that error

**Comment by abhithory** [comment]
@asim-shrestha wow... working now.... thanks....

Please let me know this also....

Now i can develop this custom sign-in page with TailwindUI components. **But** what type of design this custom sign-in page should have?? same as this next auth?? or is there any other design?

**Comment by abhithory** [comment]
hi @asim-shrestha , i have developed the sign-in page and done everything for this custom sign-in page. but I am a little bit confused about the design. 

Please let me know this so that i can make PR....

- Now i have developed this custom sign-in page with TailwindUI components. But what type of design this custom sign-in page should have?? same as this next auth?? or is there any other design?

- also do i add email sign-in also? or these providers signin is enough for now??


thanks

**Comment by abhithory** [comment]
Currently, I have developed this design...

![image](https://github.com/reworkd/AgentGPT/assets/76877003/2b9c391e-75b3-42d7-b7db-f7aa4825e5bf)

**Comment by asim-shrestha** [comment]
Hey we'd need to keep the same logo there.

<img width="319" alt="image" src="https://github.com/reworkd/AgentGPT/assets/50181239/e554eaba-3e8b-4b06-a5e9-09de14e063b2">


Lets do something like this and say: Sign in to AgentGPT. We can get rid of the middle box and lets keep the existing colours for the different providers. 

Background wise, we can do something similar to this page: https://agentgpt.reworkd.ai/secret-landing-page

**Comment by abhithory** [comment]
hi @asim-shrestha , i have developed two designs.... let me know with which one should i make PR. 

just confirm the design... Everything else is working fine... i have tested...

1)
![demo0](https://github.com/reworkd/AgentGPT/assets/76877003/2625cac4-b497-4459-9ea3-db7803367ed9)



2)
![demo1](https://github.com/reworkd/AgentGPT/assets/76877003/c4d0b003-72f3-4169-827f-4c127eae1e8e)

**Comment by abhithory** [comment]
@asim-shrestha , also let me know if there is any changes in this design??

**Comment by JPDucky** [comment]
I vote for the first design, the background on no.2 looks like every other gpt app I've seen

**Comment by abhithory** [comment]
@asim-shrestha , please confirm the  design..... or let me know if i should make the pr directly?/

**Comment by asim-shrestha** [comment]
Hey first design looks good, lets get a PR for that! @abhithory

**Comment by abhithory** [comment]
@asim-shrestha  Done Done

**Comment by jasangill1** [comment]
@abhithory Great work will close as I believe this has been merged !!!!
