### ISSUE TITLE
Unable to connect to backend. Please try again later.

### ISSUE THREAD

**Issue by Heimdallr01** [reworkd/AgentGPT#804]
When I run the agent it starts creating it's to-do list, but after "thinking" I keep getting this error:

> Unable to connect to backend. Please try again later.

No matter what I do, log-out/login, changing settings I keep getting this. This even takes up my daily runs.
I have a Pro Account and use the website.

**Comment by asim-shrestha** [comment]
Hey, mind emailing support@reworkd.ai your email. Additionally, would you mind letting us know what your `goal` is?

**Comment by mbelsis** [comment]
I have the same issue on the online version of this app...it does not matter what goal i add the result is the same.. I am a registered customer

**Comment by jasangill1** [comment]
Hello @Heimdallr01, @mbelsis 👋,

Are you guys still experiencing these issues or have they been resolved, I recommend trying the service again and trying to replicate these issues maybe the recent updates have solved this problem!!!

if not could you please provide some more details like a screenshot or copy of the console log messages would be really helpful for us to diagnose the issue. 

along with whether would you be using a VPN or have network restrictions.

Looking forward to hearing back from you both! 👀📨

**Comment by jasangill1** [comment]
Hello @Heimdallr01  @mbelsis I will be closing these issues due to inactivity, please feel free to reopen these issues if you need still need help!!
