### ISSUE TITLE
At image generation: TypeError: Cannot set properties of undefined (setting 'undefined')

### ISSUE THREAD

**Issue by liferadioat** [reworkd/AgentGPT#811]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

If an image is generated the view should consist

### Current behaviour

The view breaks when an image is generated with this error:

`TypeError: Cannot set properties of undefined (setting 'undefined')
src/components/console/ChatMessage.tsx (54:17) @ t

  52 | ) : (
  53 |   <>
> 54 |     <span>{t(message.value, { ns: "chat" })}</span>
     |           ^
  55 |     {
  56 |       // Link to the FAQ if it is a shutdown message
  57 |       message.type == MESSAGE_TYPE_SYSTEM &&
`

### Steps to reproduce

- Create a prompt, where an image should be generated

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by asim-shrestha** [comment]
Hey @liferadioat, thanks for reporting. We've now removed dynamic translations for message values

**Comment by jasangill1** [comment]
Hello @liferadioat, was wondering if you were still have the same problem or has It changed

**Comment by liferadioat** [comment]
Seems to to be solved. Thanks
