### ISSUE TITLE
Stuck at Stop Agent

### ISSUE THREAD

**Issue by EngAhmed91za** [reworkd/AgentGPT#813]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

when creating customer task it crashes then is stuck at stop agent

### Current behaviour

still stuck at "stop agent"

### Steps to reproduce

1. created a new bot
2. waiting
3. crash
![Screenshot 2023-06-16 023228](https://github.com/reworkd/AgentGPT/assets/24923960/2affb9ec-0207-42d0-a9a6-eb68162c4ec1)

### Possible solution

unknown but i tried with a different browser it's not stuck

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by AJS-8** [comment]
I'm also experiencing this issue:
![AgentGPT Running Bug](https://github.com/reworkd/AgentGPT/assets/136870733/db044617-a387-4278-bfca-ea1a26d29f53)

**Comment by asim-shrestha** [comment]
Hey thanks folks. this was an issue where we saved the Agent in the agent store so if you were running the agent and refreshed, it used the old store value but never actually ran the agent causing this state. This has since been updated, can you let me know if you're still experiencing this?

**Comment by mrwill84** [comment]
Hey Mate @asim-shrestha , 
I'm still facing this issue, could you point ways to clear the status ?

**Comment by mrwill84** [comment]
and I checked database , I removed all the agent relating row in tables . it still happens

**Comment by jasangill1** [comment]
Hello @mrwill84 if you are still experiencing these issues try clearing your browser's cache!!!

**Comment by asim-shrestha** [comment]
Hey MrWill does this have to do with a local install or is this on agentgpt.reworkd.ai?

**Comment by mrwill84** [comment]
clean all browser's cache works to me ! thank you . I'm running locally
