### ISSUE TITLE
./setup.sh

### ISSUE THREAD

**Issue by XiaoYiNew** [reworkd/AgentGPT#821]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

manifest for docker.io/semitechnologies/weaviate:1.19.6 not found

### Current behaviour

./setup.sh

### Steps to reproduce

./setup.sh

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by JPDucky** [comment]
Can you give more logs?

**Comment by jasangill1** [comment]
Hello @XiaoYiNew 👋,

Are you still experiencing issues with your local setup? 🛠

Please provide any screenshots 📸 and more information 📝 to help diagnose these issues.

**Looking forward to hearing back from you** 📨👀
