### ISSUE TITLE
ERROR retrieving initial tasks array

### ISSUE THREAD

**Issue by harishruparel** [reworkd/AgentGPT#835]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

It should run the agent and ask the text?

### Current behaviour

![image](https://github.com/reworkd/AgentGPT/assets/25629398/84137950-a4c6-40f6-bca7-79975796da17)
The agent errors out

### Steps to reproduce

Give a name for the Agent
Put the goal and 
Click Deploy Agent

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by asim-shrestha** [comment]
Hey this is an issue with your API key. Please check your plan and billing details on your OpenAI account: https://platform.openai.com/account/billing/overview
