### ISSUE TITLE
✨ Implement OpenAI functions for Start and Create tasks

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#842]
OpenAI functions are a lot more reliable in returning valid json. We have a lot of issues stemming from bad arrays and strings in our current setup

**Comment by estefysc** [comment]
Hey, @asim-shrestha, would you be able to provide me with more info about this issue? I would like to see if I can work on it.

**Comment by asim-shrestha** [comment]
Sure thing @estefysc! 

There are currently four phases that that our agents go through. This is defined in `open_ai_agent_service`.

- Start tasks: This involves asking OpenAI to return a list of strings where each string is a task. This is only run once at the start of the agent run

The following will continually loop:
- Analyze task: This involves using OpenAI functions that will return which "function" to use. A Function being the tool that will be selected (Create an image, google search, etc)
- Execute task: This involves using the tool direction with an open ai completion.
- Create task: Similar to `Start tasks`, we ask OpenAI for a single task as a string currently

This setup for start tasks will often fail because they are not parsable as an array of strings. An example from Sentry:

```
OpenAIError
Failed to parse tasks from completion '[
  "Rechercher des exemples de sites Web pour les sociétés d'évaluation immobilière",
  "Choisir un modèle de site Web adapté à la compagnie "Agent évaluation immobilière"",
  "Personnaliser le modèle choisi en ajoutant le nom de la compagnie, le logo et les informations de contact",
  "Publier le site Web sur un serveur ou une plateforme d'hébergement"
]'.
```

This failure is because one of the strings is using a double quote inside of it `"Agent évaluation immobilière"",`. We can instead use the new OpenAI function calls features similar to the `AnalyzeTask` agent and and return a list of strings directly and parse from that. 

Let me know if that helps!

**Comment by estefysc** [comment]
@asim-shrestha, thanks for the information! I can look at the code and attempt to give this a try. I am a programmer with little experience (not too sure what you think about that so let me know), but I am trying to start contributing to AI projects.

**Comment by estefysc** [comment]
@asim-shrestha the following is happening when I tried to start AgentGPT:
![image](https://github.com/reworkd/AgentGPT/assets/52083750/d6def195-b5d0-4408-8581-b7694dc2745b)

**Comment by asim-shrestha** [comment]
Hey sorry @estefysc ! Try fetching the latest changes and re-building

**Comment by asim-shrestha** [comment]
Accidentally deleted a docker-file

**Comment by estefysc** [comment]
Aaah, ok, @asim-shrestha, No worries! So now things are starting to move along, but it seems to get stuck in the process.

`[+] Running 5/5
 ✔ Network agentgpt_default       Created                                                                                                                                                                     0.8s 
 ✔ Container next                 Created                                                                                                                                                                    12.6s 
 ✔ Container agentgpt-weaviate-1  Created                                                                                                                                                                     0.3s 
 ✔ Container db                   Created                                                                                                                                                                     0.3s 
 ✔ Container platform             Created                                                                                                                                                                     0.1s 
Attaching to agentgpt-weaviate-1, db, next, platform
db                   | 2023-07-06 18:27:22+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.33-1.el8 started.
db                   | 2023-07-06 18:27:23+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db                   | 2023-07-06 18:27:23+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.33-1.el8 started.
next                 | dos2unix: wait-for-db.sh: No such file or directory
next                 | dos2unix: Skipping wait-for-db.sh, not a regular file.
next                 | cp: omitting directory '.env'
next                 | dos2unix: .env.temp: No such file or directory
next                 | dos2unix: Skipping .env.temp, not a regular file.
next                 | /entrypoint.sh: line 10: can't create .env: Is a directory
next                 | rm: can't remove '.env.temp': No such file or directory
next                 | /entrypoint.sh: line 16: ./wait-for-db.sh: not found
db                   | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
db                   | 2023-07-06T18:27:23.726582Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
db                   | 2023-07-06T18:27:23.727357Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.33) starting as process 1
db                   | 2023-07-06T18:27:23.737175Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
db                   | 2023-07-06T18:27:23.986583Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
agentgpt-weaviate-1  | {"action":"startup","default_vectorizer_module":"none","level":"info","msg":"the default vectorizer modules is set to \"none\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2023-07-06T18:27:24Z"}
agentgpt-weaviate-1  | {"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2023-07-06T18:27:24Z"}
agentgpt-weaviate-1  | {"action":"grpc_startup","level":"info","msg":"grpc server listening at [::]:50051","time":"2023-07-06T18:27:24Z"}
agentgpt-weaviate-1  | {"action":"restapi_management","level":"info","msg":"Serving weaviate at http://[::]:8080","time":"2023-07-06T18:27:24Z"}
db                   | 2023-07-06T18:27:24.386980Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db                   | 2023-07-06T18:27:24.387040Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
db                   | 2023-07-06T18:27:24.391787Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing 
a different directory.
db                   | 2023-07-06T18:27:24.428012Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
db                   | 2023-07-06T18:27:24.428094Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.33'  socket: '/var/run/mysqld/mysqld.sock'  port: 3307  MySQL Community Server - GPL.
platform             | /usr/local/bin/python: No module named reworkd_platform
next                 | 
next                 | ! unknown or unexpected option: --name
next                 | 
next                 | Apply pending migrations to update the database schema in production/staging
next                 | 
next                 | Usage
next                 | 
next                 |   $ prisma migrate deploy [options]
next                 | 
next                 | Options
next                 | 
next                 |   -h, --help   Display this help message
next                 |     --schema   Custom path to your Prisma schema
next                 | 
next                 | Examples
next                 | 
next                 |   Deploy your pending migrations to your production/staging database
next                 |   $ prisma migrate deploy
next                 | 
next                 |   Specify a schema
next                 |   $ prisma migrate deploy --schema=./schema.prisma
next                 | 
next                 | 
next                 | Schema Env Error: Error: EISDIR: illegal operation on a directory, read
next                 | Schema Env Error: Error: EISDIR: illegal operation on a directory, read
next                 | Error: Could not find a schema.prisma file that is required for this command.
next                 | You can either provide it with --schema, set it as `prisma.schema` in your package.json or put it into the default location ./prisma/schema.prisma https://pris.ly/d/prisma-schema-location 
platform exited with code 0
next                 | Schema Env Error: Error: EISDIR: illegal operation on a directory, read
next                 | prisma:warn The postinstall script automatically ran `prisma generate` and did not find your `prisma/schema.prisma`.
next                 | If you have a Prisma schema file in a custom path, you will need to run
next                 | `prisma generate --schema=./path/to/your/schema.prisma` to generate Prisma Client.
next                 | If you do not have a Prisma schema file yet, you can ignore this message.
next                 | 
next                 | 
next                 | npm
next                 |  ERR! code ENOENT
next                 | npm ERR!
next                 |  syscall open
next                 | npm ERR! path /next/package.json
next                 | npm
next                 |  ERR! errno -2
next                 | npm ERR! enoent ENOENT: no such file or directory, open '/next/package.json'
next                 | npm ERR! enoent This is related to npm not being able to find a file.
next                 | npm ERR! enoent
next                 | 
next                 | npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-07-06T18_27_28_252Z-debug-0.log
next                 | 
platform exited with code 0
next exited with code 254
platform exited with code 0
platform             | /usr/local/bin/python: No module named reworkd_platform
platform             | /usr/local/bin/python: No module named reworkd_platform
platform             | /usr/local/bin/python: No module named reworkd_platform
platform             | /usr/local/bin/python: No module named reworkd_platform
platform exited with code 1
platform             | /usr/local/bin/python: No module named reworkd_platform
platform exited with code 1
platform exited with code 1
platform             | /usr/local/bin/python: No module named reworkd_platform
platform exited with code 1
platform exited with code 1
platform             | /usr/local/bin/python: No module named reworkd_platform
platform             | /usr/local/bin/python: No module named reworkd_platform
platform             | /usr/local/bin/python: No module named reworkd_platform
platform             | /usr/local/bin/python: No module named reworkd_platform
platform             | /usr/local/bin/python: No module named reworkd_platform
platform             | /usr/local/bin/python: No module named reworkd_platform
platform             | /usr/local/bin/python: No module named reworkd_platform
platform             | /usr/local/bin/python: No module named reworkd_platform
platform             | /usr/local/bin/python: No module named reworkd_platform
platform exited with code 1`

![image](https://github.com/reworkd/AgentGPT/assets/52083750/c5ebc2d0-38e8-4060-947b-371eebc225a1)

I am on a Windows 10 Enterprise machine.

**Comment by asim-shrestha** [comment]
Let me see on my end

**Comment by estefysc** [comment]
Perfect! Thank you. Will wait to see what you find.

**Comment by asim-shrestha** [comment]
Hmm @estefysc This might be a windows related error. I just tested this on Mac with a fresh environment and everything is running correctly. Heres what I did:

- Fetched the latest AgentGPT changes (From `main`, not just the latest release)
- Deleted all of my environments / volumes / etc on docker desktop
- Ran ` docker system prune -a`
- Re-ran `./setup.sh` choosing the `docker-compose` option

Would you mind following the above steps and retrying?

**Comment by estefysc** [comment]
Ok, will do and let you know what happens. Thanks for the help!

**Comment by estefysc** [comment]
@asim-shrestha it did not work =(. Will do some investigation to see if I can figure something out.

**Comment by asim-shrestha** [comment]
Dang @estefysc, not quite sure whats wrong in this case. I know docker can be very wonky in Windows. I'd recommend searching online if anything - will be more help than I can be. 

PS, are you running through WSL?

**Comment by estefysc** [comment]
@asim-shrestha oh Windows Windows! =/ Thank you for the help though! And yes, will be trying to find something on the internet. So when I installed Docker, it prompted me to install WSL 2, which I did, and I have the Ubuntu distro. But when I am starting the app, I am just following the instructions in the Readme. I am using the terminal on VSCode, basically powershell. 

I went ahead and unassigned myself from the issue. I rather be able to run the app first.

**Comment by shubhamofbce** [comment]
@asim-shrestha I am interested in working on this. Is this still open ??

**Comment by asim-shrestha** [comment]
It's been completed already unfortunately @shubhamofbce!

**Comment by shubhamofbce** [comment]
@asim-shrestha Do you have anything major in the roadmap to work on. I am really interested to work on this or similar project on any roadmap task.
I was able to run the project and make small changes and they are working fine.
