### ISSUE TITLE
🐛 Errors when running docker-compose build

### ISSUE THREAD

**Issue by yoventures** [reworkd/AgentGPT#850]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

when running docker-compose build, the building process should complete successfully.

### Current behaviour

<img width="850" alt="Screenshot 2023-06-22 201706" src="https://github.com/reworkd/AgentGPT/assets/114469342/7795f473-e952-4459-8c7f-09abccd9fda4">

Getting the following error when running **docker-compose build**

`#0 31.48   ChefBuildError
#0 31.48
#0 31.48   Backend subprocess exited when trying to invoke get_requires_for_build_wheel
#0 31.48
#0 31.48   /bin/sh: 1: pkg-config: not found
#0 31.48   /bin/sh: 1: pkg-config: not found
#0 31.48   Trying pkg-config --exists mysqlclient
#0 31.48   Command 'pkg-config --exists mysqlclient' returned non-zero exit status 127.
#0 31.48   Trying pkg-config --exists mariadb
#0 31.48   Command 'pkg-config --exists mariadb' returned non-zero exit status 127.
#0 31.48   Traceback (most recent call last):
#0 31.48     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#0 31.48       main()
#0 31.48     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#0 31.48       json_out['return_val'] = hook(**hook_input['kwargs'])
#0 31.48     File "<string>", line 27, in find_package_name
#0 31.48   Exception: Can not find valid pkg-config name.
#0 31.48   Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
#0 31.48
#0 31.48
#0 31.48   at /usr/local/lib/python3.11/site-packages/poetry/installation/chef.py:152 in _prepare
#0 31.49       148│
#0 31.49       149│                 error = ChefBuildError("\n\n".join(message_parts))
#0 31.49       150│
#0 31.49       151│             if error is not None:
#0 31.49     → 152│                 raise error from None
#0 31.49       153│
#0 31.49       154│             return path
#0 31.49       155│
#0 31.49       156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
#0 31.49
#0 31.49 Note: This error originates from the build backend, and is likely not a problem with poetry but with mysqlclient (2.2.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "mysqlclient (==2.2.0)"'.
#0 31.49
------
failed to solve: executor failed running [/bin/sh -c poetry install --only main]: exit code: 1`

### Steps to reproduce

1. Follow the readme instructions for install or run ```
git clone https://github.com/reworkd/AgentGPT.git && cd AgentGPT
./setup.sh
```
2. Observe the error

### Possible solution

found this [SO thread](https://stackoverflow.com/questions/76533384/docker-alpine-build-fails-on-mysqlclient-installation-with-error-exception-can), which seem to mention a similar issue, but the proposed solution did not work.


### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [X] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Daniel-Trung-Nguyen** [comment]
I got the same error trying to install on a mac

**Comment by divineslight** [comment]
Same error on Mac

**Comment by timtischler** [comment]
Same error on windows inside of ubuntu WSL2 instance.

**Comment by timtischler** [comment]
I created a PR with a fix for this issue.  Resyncing the repo removed a required dependency.  If anyone wants to get it running before the PR is approved, it's a one line fix.

**Comment by yoventures** [comment]
@timtischler , I've tried your suggested change. it passes that first error but there are still a bunch of other ones that prevents the backend platform for working (see below). there may be something bigger going on with this setup file.

<img width="580" alt="Screenshot 2023-06-23 183536" src="https://github.com/reworkd/AgentGPT/assets/114469342/d6d97739-8a82-422f-9b9f-cf4952a4ca2f">

`platform             | Traceback (most recent call last):
platform             |   File "<frozen runpy>", line 198, in _run_module_as_main
platform             |   File "<frozen runpy>", line 88, in _run_code
platform             |   File "/app/src/reworkd_platform/__main__.py", line 1, in <module>
platform             |     import uvicorn
platform             | ModuleNotFoundError: No module named 'uvicorn'
platform exited with code 1`

**Comment by sunrays2993** [comment]
Same here on Windows 10. Have use the 'setup.bat' method and the 'docker-compose build'

**Comment by p6002** [comment]
This project not working for months.

**Comment by asim-shrestha** [comment]
Thanks @timtischler, I've done a full system prune on docker and removed all my existing containers and i'm not getting any errors on main at the moment. Can you (@yoventures and @p6002) try fetching the latest changes and letting me know if you're still facing issues?

**Comment by yoventures** [comment]
the recent commits fixed my issues. thank you.

**Comment by p6002** [comment]
I tried to get it up and running yesterday after a month and no success.
The documentation is not complete, which only adds to the frustration.

**Comment by asim-shrestha** [comment]
Nice @yoventures!

@p6002 Sorry about this. How are you running it? Are you using the setup scripts which will guide you through environment setup? Are you using `docker-compose` which will setup all required infra for you?

**Comment by dollkwong** [comment]
I am installing it with poetry in a docker. I am still facing the same error message. 
```
#12 768.5 Note: This error originates from the build backend, and is likely not a problem with poetry but with mysqlclient (2.2.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "mysqlclient (==2.2.0)"'.
#12 768.5
------
executor failed running [/bin/sh -c poetry install --no-root --only main]: exit code: 1
```
is it not updated in pypi?

**Comment by asim-shrestha** [comment]
We don't have anything on pypi as far as i'm aware. Your best bet is to purge everything (delete everything and delete containers) and re run the new setup installation from https://docs.reworkd.ai/development/setup

It is an interactive CLI @dollkwong

**Comment by gabrielzencha** [comment]
try installing libmysqlclient-dev before installing any mysql python package
sudo apt-get install libmysqlclient-dev

**Comment by asim-shrestha** [comment]
```
RUN apt-get update && apt-get install -y \
  default-libmysqlclient-dev \
  pkg-config \
  gcc \
  pkg-config \
  && rm -rf /var/lib/apt/lists/*
  ```

The container should already have that installed @gabrielzencha 🤔

**Comment by asim-shrestha** [comment]
So the docker files should contain this, otherwise if you're running locally you might need to run the following

```
brew install pkg-config
brew install mysql
```

Closing!

**Comment by iamXaidar** [comment]
If you run your project local (without docker) use the last version of mysqlclient. If you run project by docker build poetry with mysqlclient=2.1.0
