### ISSUE TITLE
🗄 Update Dropdown Menu in Prompt Template Misplacement and Functionality

### ISSUE THREAD

**Issue by jasangill1** [reworkd/AgentGPT#870]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/reworkd/AgentGPT/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/reworkd/AgentGPT/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Users have been experiencing an issue with the dropdown menu in the prompt templates. Instead of operating as a typical dropdown menu where the selected category appears at the top, the current implementation causes the dropdown box to behave strangely.

When an option is selected from the menu, the dropdown box moves to the middle of the list. This action disrupts the user experience and can lead to confusion when selecting categories.

<img width="423" alt="Screen Shot 2023-06-26 at 9 21 22 PM" src="https://github.com/reworkd/AgentGPT/assets/56135840/76d83772-bd00-4b9e-90ba-851da90d2f9c">

### ✔️ Solution

Proposed Solution

- Correct Dropdown Behavior: The dropdown menu should be reconfigured so that when a user selects an option, it appears at the top of the menu. This is the expected behavior for a dropdown menu and is more user-friendly.

- Positioning of the Dropdown Box: The placement of the dropdown box should be adjusted. Instead of moving to the middle of the menu, it should remain static and in the correct position regardless of the option selected.

- User Interface (UI) Design: It might be beneficial to review and update the overall design and functionality of the dropdown menu. This includes its visual appearance, how it interacts with user commands, and how it displays the selected options.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by abhithory** [comment]
hi @jasangill1, i can fix this dropdown issue. can you please assign me issue?

**Comment by jasangill1** [comment]
Hello @abhithory i have assigned you  the issue!! feel free to reach on anything you need help with !!!!!

**Comment by abhithory** [comment]
@jasangill1 ok thanks

**Comment by abhithory** [comment]
hi @jasangill1, is this the behavior that you want from the dropdown? 

- or `All` option also changes its position??
- currently, I am always placing `All`  at the top and changing other categories accordingly.
- 
https://github.com/reworkd/AgentGPT/assets/76877003/b31774ed-6197-43ec-a360-f632b100959b

**Comment by abhithory** [comment]
- also i am not getting the wrong placement of the dropdown. it is not going to the middle of the menu. i have tested responsiveness also

**Comment by jasangill1** [comment]
Hello @abhithory That is strange it seems that on windows this problem does not occur but on mac it does, I guess it would be kind of hard for you to troubleshoot if you can't see the problem. Don't worry about this then I will look into it!! feel free to finding another issue or attempting to syle it a bit better!!

**Comment by abhithory** [comment]
hi @jasangill1 ,

- I have tested this on both Windows and Ubuntu and there it is working fine. so, maybe it shows the problem in Mac only.
- also the style is also a little bit different in the screenshot. (there is a tick icon in the screenshot that is not showing in my browser in Windows/ubuntu)

- i think this issue is related `Select and Option` that we are using in the dropdown. Maybe it is rendered differently.


### - so now should i just style it a little better or leave it as it is or make a custom dropdown without using `Select and Option`??

**Comment by jasangill1** [comment]
Closing as issue only happens on mac, will create new ticket explaining this!
