### ISSUE TITLE
tRPC failed on tools.getUserTools: connect ECONNREFUSED ::1:80

### ISSUE THREAD

**Issue by Aphiticus** [reworkd/AgentGPT#873]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

I am running on Windows:

While running from codespaces i input the following in terminal: bash ./setup.sh --local.  I then input my key. 

I am able to go to: http://localhost:3000 and everything appears to run.  

### Current behaviour

Attempting to run AgentGPT in the local URL it doesnt work due to the key.   

I receive the following error in the terminal: tRPC failed on tools.getUserTools: connect ECONNREFUSED ::1:80.  

I also get the same error running from Visual Studio. 
I am a student developer, so a bit lost on this part.  There might be an easy fix.  Any help is greatly appreciated.  

### Steps to reproduce

1. Run AgentGPT in Codespaces
2. Run bash ./setup.sh --local
3. Insert OpenAI Key.
4. Go to http://localhost:3000
5. Attempt to use AgentGPT without success.  

### Possible solution

I think its a network issue not letting my communicate.  

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by jasangill1** [comment]
Hello @Aphiticus would you be able to go to your `.env` file and input your API key there, try running it again, please let me know if this helped!!

**Comment by Aphiticus** [comment]
Jasangill,  

I was able to get it working by replacing all of the files with fresh one's.  Somewhere along the way i messed up the files.  

Thank you for your reply.

Aphiticus.
