### ISSUE TITLE
reworkd_platform.web.api.errors.OpenAIError: -351 is less than the minimum of 1 - 'max_tokens'

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [reworkd/AgentGPT#878]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

I encoutered this issue when running the docker. 
Thanks,
Daniel
<img width="953" alt="image" src="https://github.com/reworkd/AgentGPT/assets/22897462/6e9df5b7-d9cc-48af-a36f-bf237d7e0bc9">

### Current behaviour

doesn't seem to produce any results

### Steps to reproduce

run the containter and put in a task

### Possible solution

I don't know

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by asim-shrestha** [comment]
Thanks @Daniel-Trung-Nguyen! Will take a look

**Comment by awtkns** [comment]
HI @Daniel-Trung-Nguyen, I was able to reproduce the issue! In the short term this can be fixed by increasing the MAX_TOKENS on the settings page.
