### ISSUE TITLE
🗎 Create a Detailed Authentication Documentation

### ISSUE THREAD

**Issue by jasangill1** [reworkd/AgentGPT#886]
### What piece of documentation is affected?

Users have reported difficulties in understanding how our authentication works. Updating the documentation will reduce these challenges, enhance user understanding, and improve the overall user experience.

**Proposed Solution**

To enhance user experience, we suggest the following updates:

1. **Authentication Documentation Revision:** Streamline our existing authentication guide, focusing on local vs production authentication. Detail their differences, use cases, and transition process.

2. **Social Sign-in Activation:** Incorporate a detailed, visually aided guide on social sign-in activation.

3. **NextAuth Resources:** Provide links to NextAuth resources and tutorials to aid user understanding of its role in our application. Relevant resources can be found at [NextAuth Introduction](https://next-auth.js.org/getting-started/introduction).

4. **Testing and Validation:** Post-update, conduct user tests and solicit feedback to confirm the documentation clarity and effectiveness.

5. **Production auth vs Local Auth:** Describe the difference between the too

Reference linked to setting up auth adam goes over how to set it up with picture: 
https://github.com/reworkd/AgentGPT/issues/480

**Comment by jasangill1** [comment]
created Auth Page in docs !!

**Comment by tilllt** [comment]
https://docs.reworkd.ai/development/auth

**Comment by R2Pitou** [comment]
I wish I could use this amazing sounding project locally on my own machine without the F****ng login prompt that even in development mode causes an error.

I've tried to run AgentGPT container dozens of times and never managed to get past the Reworkd insecure login without crashing and burning.

I've grown to hate that horizontal fish hook so much I'm about to give up on this.

Steps to reproduce:
Run setup.bat
"To make the application use the insecure, simple version of authentication, set the NEXTAUTH_SECRET variable in your .env file to a simple, insecure value (e.g., “changeme”)."

```
.env:
# Platform Config: (max loops determines how many times the agent may execute)
NEXT_PUBLIC_MAX_LOOPS="100"
REWORKD_PLATFORM_MAX_LOOPS=${NEXT_PUBLIC_MAX_LOOPS}

# Deployment Environment:
NODE_ENV="development"
NEXT_PUBLIC_VERCEL_ENV="${NODE_ENV}"

# NextJS:
NEXT_PUBLIC_BACKEND_URL="http://localhost:8000"

# Next Auth config:
NEXTAUTH_SECRET=changeme
NEXTAUTH_URL="http://localhost:3000"

# Auth providers (Use if you want to get out of development mode sign-in):
GOOGLE_CLIENT_ID="***"
GOOGLE_CLIENT_SECRET="***"
GITHUB_CLIENT_ID="***"
GITHUB_CLIENT_SECRET="***"
DISCORD_CLIENT_SECRET="***"
DISCORD_CLIENT_ID="***"
```
Run setup.bat
```
frontend     | Invalid `p.user.findUnique()` invocation in
frontend     | /next/node_modules/@next-auth/prisma-adapter/dist/index.js:210:43
frontend     |
frontend     |   207 return {
frontend     |   208     createUser: (data) => p.user.create({ data }),
frontend     |   209     getUser: (id) => p.user.findUnique({ where: { id } }),
frontend     | → 210     getUserByEmail: (email) => p.user.findUnique(
frontend     | Can't reach database server at `db`:`3307`
frontend     |
frontend     | Please make sure your database server is running at `db`:`3307`.
frontend     | API handler should not return a value, received object.
frontend     | API handler should not return a value, received object.
frontend     | API handler should not return a value, received object.
frontend     | API handler should not return a value, received object.
```

![image](https://github.com/reworkd/AgentGPT/assets/101490847/1a25de44-8d8c-4fc9-9b84-8c95d6af190b)

Open localhost:3000

After clicking anything, get redirected to a login page (I just wish this didn't exist at all. Let people make their own walled gardens.)
http://localhost:3000/signin?callbackUrl=http%3A%2F%2Flocalhost%3A3000%2F
![image](https://github.com/reworkd/AgentGPT/assets/101490847/63ece1aa-8f8c-4f9c-95e4-b5f5c639d361)

Pass changeme as username and receive Error page. 
Land on Error Page
http://localhost:3000/api/auth/error?error=%0AInvalid%20%60p.user.findUnique()%60%20invocation%20in%0A%2Fnext%2Fnode_modules%2F%40next-auth%2Fprisma-adapter%2Fdist%2Findex.js%3A210%3A43%0A%0A%20%20207%20return%20%7B%0A%20%20208%20%20%20%20%20createUser%3A%20(data)%20%3D%3E%20p.user.create(%7B%20data%20%7D)%2C%0A%20%20209%20%20%20%20%20getUser%3A%20(id)%20%3D%3E%20p.user.findUnique(%7B%20where%3A%20%7B%20id%20%7D%20%7D)%2C%0A%E2%86%92%20210%20%20%20%20%20getUserByEmail%3A%20(email)%20%3D%3E%20p.user.findUnique(%0ACan%27t%20reach%20database%20server%20at%20%60db%60%3A%603307%60%0A%0APlease%20make%20sure%20your%20database%20server%20is%20running%20at%20%60db%60%3A%603307%60.

![image](https://github.com/reworkd/AgentGPT/assets/101490847/dbe35b11-a4e2-4c39-b625-0e6ce59e5e7b)

Check, re-check and double-check your spelling of changeme. Question your sanity and all memories of good times, consider leaving everything behind to become a mountain hermit, transcribing the cosmic radiation of the universe for food donations.

Finally, close docker, touch grass and hate the fact that a branded login page was more important than a database connection test.

**Comment by jasangill1** [comment]
@R2Pitou Delete the docker volumes and re build the container this should fix it
