### ISSUE TITLE
🗝️ Validation for User Keys in setup.sh script

### ISSUE THREAD

**Issue by jasangill1** [reworkd/AgentGPT#892]
### 🔖 Feature description

During the setup process, users are currently responsible for the correctness of the keys they enter. However, this leaves room for human error and can lead to unsuccessful setups due to invalid keys.

### ✔️ Solution

Integrating a validation step for the keys within the setup.sh script itself. This step would automatically verify the accuracy of the keys as users input them, reducing the risk of errors and subsequent setup issues.

This solution would involve:

1. Implementing a key validation function within the setup.sh script.
2. Testing the new function to ensure its effectiveness and reliability.
3. Updating the setup documentation to inform users of this new feature.

By integrating a key validation step directly into the setup process, we can significantly improve the user experience and minimize setup-related issues.

**Comment by MusabShakeel576** [comment]
@jasangill1, instead of adding validation logic in setup.sh, it would be better to leverage already existing AgentGPT CLI and add `validate` methods similar to OpenAIApiKey in both [serpApiKey and replicateApiKey objects](https://github.com/reworkd/AgentGPT/blob/83589430b470c29751f1f42a62f2d0860608ac93/cli/src/questions/newEnvQuestions.js#L19-L30).

**Comment by jasangill1** [comment]
Hello @MusabShakeel576 Sorry if my instructions were unclear but that was the intention would you like to tackle this issue I will assign it to you if so!!!

Feel free to reach out if you com across any troubles !!!

**Comment by MusabShakeel576** [comment]
@jasangill1 no worries. Sure, I'll look into it.

**Comment by jasangill1** [comment]
Hello @MusabShakeel576 Feel free to message me whenever you need help!!

**Comment by MusabShakeel576** [comment]
@jasangill1 pushed, and please answer the question I mentioned in the second point in PR description.

**Comment by jasangill1** [comment]
Hello @MusabShakeel576 Sounds good ill get @asim-shrestha to review!!

**Comment by jasangill1** [comment]
Great work @MusabShakeel576 going to close this issue as you have completed it!!!
