### ISSUE TITLE
Database URL/Schema mismatch

### ISSUE THREAD

**Issue by jihlenburg** [reworkd/AgentGPT#9]
It seems like there's a mismatch for the database URL in the prism schema:

`> npx prisma db push
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database

Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
  -->  schema.prisma:7
   | 
 6 |     provider = "postgresql"
 7 |     url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
[Context: getConfig]`

**Comment by bthibault** [comment]
+1

**Comment by Bill-Niz** [comment]
+1

**Comment by mrayonnaise** [comment]
I applied the fix from the pull request linked above and was successful. Thanks, @barnjamin

**Comment by mrayonnaise** [comment]
@Srijan-Subedi please review the pull request and apply it when possible

**Comment by mrayonnaise** [comment]
Just in case someone sees this but doesn't look in the PR from @barnjamin I wanted to note that there is a larger discussion about configurability being discussed there.

**Comment by YoleYu** [comment]
Cloned the latest code, but the same error. 2023/04/1210:10:54 UTC+8

**Comment by mrayonnaise** [comment]
> Cloned the latest code, but the same error. 2023/04/1210:10:54 UTC+8

You will want to use the code from the PR [HERE](https://github.com/reworkd/AgentGPT/pull/11) before doing the `push migrations` step in the README and you should be good.

**Comment by mrayonnaise** [comment]
Did you apply the update from the PR listed [here](https://github.com/reworkd/AgentGPT/pull/11)?

**Comment by asim-shrestha** [comment]
Hey folks, AFAIK we're planning to use PostgreSQL/mysql for prod which is why its like this. I'm told an env doesn't work for the provider. Will look into it more tomorrow

**Comment by headdaotw** [comment]
this is chatgpt told me:
1.首先，在 .env 文件中设置 DATABASE_URL 为 SQLite 数据库文件。例如：
DATABASE_URL=file:./dev.db
2.接下来，在 prisma/schema.prisma 文件中，将数据源更改为 SQLite。将 provider 改为 "sqlite"，如下所示：
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}
4.将 prisma/schema.prisma 文件中的以下行：
refresh_token     String?
access_token      String?
id_token          String?
5.再次运行 npx prisma db push

IT WORKS!!
