### ISSUE TITLE
🦅 Navbar Component for the landing page 

### ISSUE THREAD

**Issue by jasangill1** [reworkd/AgentGPT#905]
## Build out a navbar component:

- **Navbar Component**: The first component we need to construct is a navigation bar (navbar). This will be the primary means for users to navigate through our website.

- **Design**: The navbar design should follow the structure shown in the provided images. Please ensure the styling matches the images as closely as possible.

- **Light and Dark Mode Toggle**: Include a button for toggling between light and dark mode on the navbar. For this stage of development, we don't need to implement the functionality behind the light and dark mode switch. Focus on the aesthetics and placement of this button.

- **Responsiveness**: Please ensure that the navbar is responsive and maintains its design integrity across various screen sizes and devices.

- **Links**: Attach all links accordingly 

REMINDER: Remember to use the in-app components like buttons, inputs, combo box, and dialog box wherever need be these can be found in the /ui file.

![Navbar Design](https://github.com/reworkd/AgentGPT/assets/56135840/d83861dd-9239-4348-9997-a5a970cb6851)

**Comment by awtkns** [comment]
Just to add to this the nav bar should not be sticky

**Comment by abhithory** [comment]
@jasangill1, I want to work on this... can you please assign me this issue?

**Comment by jasangill1** [comment]
Created this nav bar but now changing to a newly designed nav bar
