### ISSUE TITLE
🗜 Information Component for Landing Page

### ISSUE THREAD

**Issue by jasangill1** [reworkd/AgentGPT#907]
## Landing Page Sectional Component

Please follow the instructions below to build the sectional component for the landing page:

### Features:

- **Layout:** The sectional component should seamlessly follow the hero section. It should include separate sections to discuss different features or aspects of our product/service, clearly labeling the main features of our application.

- **Section Headers:** This section should have a clear header stating "Your personal AI Assistant".

- **Sub Title Content:** States clearly "A platform that creates customized AI assistants to streamline your business processes and supercharge your productivity".

- **Design:** Maintain consistent spacing and alignment across sections for a clean, organized appearance. Don't worry too much about the background.

-**REMINDERS:** Remember to use the in-app components like buttons, inputs, combo box, and dialog box wherever need be these can be found in the `/ui` file

<img width="887" alt="Screen Shot 2023-06-29 at 11 12 23 PM" src="https://github.com/reworkd/AgentGPT/assets/56135840/89d136ea-da51-4c09-844f-af8ddbf328bb">

**Comment by abhithory** [comment]
hello @jasangill1, I want to work on this. can you please assign me?

- is the image available that is shown in the reference design?
- also is there a Figma design for this?
-

**Comment by jasangill1** [comment]
closed as landing has changed will reopen if we will need these
