### ISSUE TITLE
🎬 Action Component for Landing Page

### ISSUE THREAD

**Issue by jasangill1** [reworkd/AgentGPT#909]
## Features:

1. **Action Component**: The action component will be used to highlight key features or actions users can take on our platform. This component should use a `router. push` to get it to the application page and have name and goal stores.

2. **Design**: Each action point within the component should consist of an icon, a title, and a brief description. The design should be clean, straightforward, and visually appealing. Their positioning is crucial — they should be centered within the action point.

3. **Icon**: Place an icon at the top of the action point. The icon should visually represent the action or feature being described.

4. **Title**: Prepare an annual report

5. **Description**: "See What Great Tasks Our AI Assistant Can Help You Accomplish"

6. **Responsiveness**: Make sure the action component is responsive and maintains its design integrity across various screen sizes and devices.

_Reminders_: Use the in-app components and styles available in the /ui file whenever necessary.

<img width="941" alt="Screen Shot 2023-06-30 at 12 37 58 AM" src="https://github.com/reworkd/AgentGPT/assets/56135840/9bff0303-5c57-4399-a79c-0ba57c6a0fa4">

**Comment by abhithory** [comment]
@asim-shrestha ,

- is the background of this component is an image??

**Comment by asim-shrestha** [comment]
Lets hold off on this for now @abhithory. Still deciding how we want to move forward with the page :)

**Comment by jasangill1** [comment]
Closing as the plans have changed will reopen if we want to go forward with this
