### ISSUE TITLE
🔑 Running agentgpt after simple login gives Authentication Error in vps environment

### ISSUE THREAD

**Issue by conman777** [reworkd/AgentGPT#922]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

I found this bug to be similar but that runs in a local environment - https://github.com/reworkd/AgentGPT/issues/884

I expect to be able to use agentgpt after login as usually with local environment.

### Current behaviour

![Screenshot 2023-07-01 at 13 58 54](https://github.com/reworkd/AgentGPT/assets/131461235/8d943038-4bbc-490f-8d36-9b7d134acab3)

after normal ./setup.sh installation and changing localhost:port lines in each .env location to the vps dns name and logging in through the "insecure' and trying to run a prompt that is the error you get above.  

### Steps to reproduce

run on vps, ubuntu 22.04.2 LTS -CLOUD VPS S on contabo.com, follow setups below 

after normal ./setup.sh installation and changing localhost:port lines in each .env location to the vps dns name and logging in through the "insecure' and trying to run a prompt that is the error you get above

### Possible solution

Asmin thinks it could be a backend database issue.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Wetradetogether** [comment]
Same problem!

**Comment by asim-shrestha** [comment]
Hey folks, some background here:

- So we use both the backend on NextJS and the backend in Python. The NextJS backend is used almost entirely for Auth
- Authentication is handled via NextAuth in the NextJS backend. It will authenticate the user, create a session record in the database, and then the session will be passed back to the user and placed within subsequent requests to the Python backend via the authorization header
- The backend will parse the authorization header and validate it against the database to see if the user is truly signed in, if they aren't, we get the above error response

**Comment by Wetradetogether** [comment]
The user is logged in and authenticated although the error reoccurs.
Look that.
![AgentGPT (2)](https://github.com/reworkd/AgentGPT/assets/130745565/d3b9c731-04c8-49b8-8bfd-73049aa90672)

**Comment by asim-shrestha** [comment]
Yeah its a bit confusing @Wetradetogether. The reason was mentioned above

> So we use both the backend on NextJS and the backend in Python. The NextJS backend is used almost entirely for Auth

> Authentication is handled via NextAuth in the NextJS backend. It will authenticate the user, create a session record in the database, and then the session will be passed back to the user and placed within subsequent requests to the Python backend via the authorization header

So although you are logged in to the site (Through NextAuth), the backend doesn't think that its a real auth token. Perhaps your backend is talking to the incorrect database? It seems the frontend is connecting to the backend just fine. You would need to connect to the same database the backend is connecting to, and see if the session token is available

Happy to jump on a call and try to resolve this.

**Comment by maximedrn** [comment]
Hi, @asim-shrestha, I read this issue and it seems I'm facing something similar: I'm not able to start the initial task, exactly as indicated in the second log message in the @Wetradetogether's screenshot (above).

I looked at the Python code and it seems correct - I've even tried deleting the `start_task()` function to ensure that the script reaches it when starting a new task, and the function is indeed called: error 404 when it no longer exists, and 407 when the required parameters are incorrect - so I think it comes from what you said in this message:

> So although you are logged in to the site (Through NextAuth), the Python backend doesn't think that its a real auth token therefore returns this not authenticated error. Perhaps your backend is talking to the incorrect database? It seems the frontend is connecting to the backend just fine. You would need to connect to the same database the backend is connecting to, and see if the session token is available

Unfortunately, I have no idea how to fix this, I've modified several things, tried debugging the tool but I can't get past "Thinking"...
Every time I restart the tool, the backend only grants me a single POST to `/api/agent/start/` (which remains in Pending - DevTools), all other calls aren't even displayed in the console.

If you have time, can you tell me what's wrong with my configuration, I've posted an error waiting for an answer: https://github.com/reworkd/AgentGPT/issues/968

**Comment by asim-shrestha** [comment]
Replying in the other ticket!

**Comment by jasangill1** [comment]
Closing as conversation in another issue. Feel free to reopen this issue if other issue isnt clear!!!
