### ISSUE TITLE
Shell scripts doesn't work on NixOS when used as instructed

### ISSUE THREAD

**Issue by MichaelBergquistSuarez** [reworkd/AgentGPT#954]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

Running `./setup.sh` should work, even if the user doesn't happen to have `bash` or `sh` located at `/bin/bash`

### Current behaviour

Running `./setup.sh` result in error:
```
zsh: ./setup.sh: bad interpreter: /bin/bash: no such file or directory
```

![image](https://github.com/reworkd/AgentGPT/assets/3028411/c6db5883-62e9-4e4c-bad5-1c647e18f5d9)

### Steps to reproduce

1. Use a system where `bash` is not located in `/bin/bash`. You could move the file on your system, use a VM with NixOS  or some other system with the same feature if you don't have it available and want to try
2. cd into the root as instructed in readme.md
3. Run `./setup.sh`

### Possible solution

Use shebangs like  `#!/usr/bin/env bash` which are generally considered better practice, because it's more portable

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by asim-shrestha** [comment]
Handled in #955, thanks again @MichaelBergquistSuarez !
