### ISSUE TITLE
⁉️ Create an FAQ section on the manage page

### ISSUE THREAD

**Issue by jasangill1** [reworkd/AgentGPT#956]
Create a FAQ section on the manage account page to make it easier for users to get any questions answered as they are thinking about getting the Subscription, Maybe even make Discord more prominent so that users can join and ask questions to us directly!! 

<img width="1428" alt="Screen Shot 2023-07-03 at 9 22 12 AM" src="https://github.com/reworkd/AgentGPT/assets/56135840/7fc23515-8a4d-44f8-8075-a48238be4d71">

**Comment by abhithory** [comment]
@jasangill1, can you please describe a little bit more what you want to add instead of this text??

- do you want to add a button to redirect to the Discord channel?

**Comment by jasangill1** [comment]
Hello @abhithory so we would like to maybe add a button or link depending on what looks better to our docs/FAQ page. This is a great issue for you to tackle let me know if you would like to and I can assign you

**Comment by jasangill1** [comment]
Task completed !!!
