### ISSUE TITLE
🐛Model input label overflow

This is currently occurring on mobile and small screens. 

### ISSUE THREAD

**Issue by awtkns** [reworkd/AgentGPT#98]
![Screenshot_20230414-034049.png](https://user-images.githubusercontent.com/32209255/231921373-9082aefb-11b8-44b1-b05d-3795e687c580.png)

**Comment by rahul-ghimire-au6** [comment]
have raised the pr for this issue (https://github.com/reworkd/AgentGPT/pull/124)
