### ISSUE TITLE
failed to solve: failed to read dockerfile

### ISSUE THREAD

**Issue by VectorZhao** [reworkd/AgentGPT#984]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

run docker

### Current behaviour

(base) ➜  AgentGPT git:(main) ./setup.sh --docker

up to date, audited 154 packages in 609ms

30 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> agentgpt-cli@1.0.0 start
> node src/index.js

 █████╗  ██████╗ ███████╗███╗   ██╗████████╗ ██████╗ ██████╗ ████████╗
██╔══██╗██╔════╝ ██╔════╝████╗  ██║╚══██╔══╝██╔════╝ ██╔══██╗╚══██╔══╝
███████║██║  ███╗█████╗  ██╔██╗ ██║   ██║   ██║  ███╗██████╔╝   ██║   
██╔══██║██║   ██║██╔══╝  ██║╚██╗██║   ██║   ██║   ██║██╔═══╝    ██║   
██║  ██║╚██████╔╝███████╗██║ ╚████║   ██║   ╚██████╔╝██║        ██║   
╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═══╝   ╚═╝    ╚═════╝ ╚═╝        ╚═╝   
                                                                      
Welcome to the AgentGPT CLI! This CLI will generate the required .env files.
Copies of the generated envs will be created in `./next/.env` and `./platform/.env`.

Existing ./next/env file found. Validating...
? How will you be running AgentGPT? 🐋 Docker-compose (Recommended)
[+] Building 0.1s (8/8) FINISHED                                                                                                                                                                
 => [agentgpt-docs internal] load build definition from Dockerfile                                                                                                                         0.0s
 => => transferring dockerfile: 2B                                                                                                                                                         0.0s
 => [agentgpt-docs internal] load .dockerignore                                                                                                                                            0.1s
 => => transferring context: 2B                                                                                                                                                            0.0s
 => CANCELED [agentgpt-platform internal] load .dockerignore                                                                                                                               0.1s
 => CANCELED [agentgpt-platform internal] load build definition from Dockerfile                                                                                                            0.1s
 => CANCELED [mysql:8.0 internal] load build definition from Dockerfile                                                                                                                    0.0s
 => CANCELED [mysql:8.0 internal] load .dockerignore                                                                                                                                       0.0s
 => CANCELED [agentgpt-next internal] load .dockerignore                                                                                                                                   0.0s
 => CANCELED [agentgpt-next internal] load build definition from Dockerfile                                                                                                                0.0s
failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount2900618389/Dockerfile: no such file or directory

### Steps to reproduce

git clone
cd agentgpt
./setup.sh --docker

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Gsciarra** [comment]
Same on `macOS`

**Comment by Gsciarra** [comment]
I made a PR to fix this issue. In the meantime, you can remove
```YAML
  docs:
    build: ./docs
    ports:
      - "3001:3001"
```
from your `docker-compose.yml`

**Comment by asim-shrestha** [comment]
Sorry @vipervs @Gsciarra @VectorZhao! Updated our docs to mintlify and accidentally deleted the docker file. Thanks @maximedrn!
