### ISSUE TITLE
😵‍💫 Initial page load light mode and columns glitch

### ISSUE THREAD

**Issue by jasangill1** [reworkd/AgentGPT#994]
As a user on initial load the flash of the light mode navbar and columns is distracting and takes away from user experience.

https://github.com/reworkd/AgentGPT/assets/56135840/74c32945-2ec5-4021-b44e-0e620bbedc4a

**Comment by abhithory** [comment]
hi @jasangill1, I tried but this issue is not showing in my local development. 

- is this not showing in local development or is it not showing only in my pc?

**Comment by jasangill1** [comment]
hi @abhithory could you try production and see if the issue is there?

**Comment by abhithory** [comment]
@jasangill1 , yes, it is showing when I open the website from URL. but when I visit website locally (in both development and production mode) then it is not showing glitch and light mode

**Comment by jasangill1** [comment]
Hello @abhithory Well that's apart of the problem figuring out what is causing this, comparing the other components whit the theme and seeing why they arent doing this on the initial load, troubleshooting and try to find the source of the problem

**Comment by abhithory** [comment]
@jasangill1  ok, got it. let me try

**Comment by kevinlu1248** [comment]
Hey I got Sweep (https://github.com/sweepai/sweep), an AI junior dev, to make a potential fix at https://github.com/kevinlu1248/AgentGPT/pull/8. Feel free to leave a comment on the PR or in the code prefixed with "Sweep:" and it will automatically get addressed by Sweep.

I also made a PR to this repo at https://github.com/reworkd/AgentGPT/pull/1099.

**Comment by kevinlu1248** [comment]
Hey made another one at https://github.com/reworkd/AgentGPT/pull/1116
